spec: blackmagic-streaming
telemetry: stream-settings
inbound: "STREAM SETTINGS:\nAvailable Video Modes: Auto, 1080p23.98, 1080p24, 1080p25, 1080p29.97, 1080p30,\
  \ 1080p50, 1080p59.94, 1080p60, 720p25, 720p30, 720p50, 720p60\nVideo Mode: 1080p59.94\nCurrent Platform:\
  \ YouTube\nCurrent Server: Primary\nCurrent Quality Level: Streaming Medium\nStream Key: abc1-def2-ghi3-jkl4-mno5\n\
  Password: \nCurrent URL: srt://192.168.8.51\nCustomizable URL: true\nAvailable Default Platforms: YouTube\
  \ RTMP, YouTube SRT (Beta), Facebook, Twitch\nAvailable Custom Platforms: My Platform\nAvailable Servers:\
  \ Primary, Secondary\nAvailable Quality Levels: Streaming High, Streaming Medium, Streaming Low\n\n"
expect_state:
  stream:
    available_video_modes: Auto, 1080p23.98, 1080p24, 1080p25, 1080p29.97, 1080p30, 1080p50, 1080p59.94,
      1080p60, 720p25, 720p30, 720p50, 720p60
    video_mode: 1080p59.94
    platform: YouTube
    server: Primary
    quality_level: Streaming Medium
    key: abc1-def2-ghi3-jkl4-mno5
    password: ''
    url: srt://192.168.8.51
    customizable_url: true
    available_default_platforms: YouTube RTMP, YouTube SRT (Beta), Facebook, Twitch
    available_custom_platforms: My Platform
    available_servers: Primary, Secondary
    available_quality_levels: Streaming High, Streaming Medium, Streaming Low
