spec: blackmagic-multiview
telemetry: configuration-capitalised
inbound: 'CONFIGURATION:

  Layout: SOLO

  Solo enabled: True

  Display border: False


  '
expect_state:
  config:
    layout: SOLO
    solo_enabled: true
    display_border: false
