spec: mediamtx
telemetry: global-config
inbound_http:
  path: /v3/config/global/get
  body: '{"logLevel":"info","authMethod":"internal","api":true,"rtsp":true,"rtmp":true,"hls":true,"webrtc":true,"srt":true,"moq":false,"playback":false,"metrics":true,"rtspAddress":":8554","rtspsAddress":":8322","rtmpAddress":":1935","rtmpsAddress":":1936","hlsAddress":":8888","webrtcAddress":":8889","srtAddress":":8890","playbackAddress":":9996","metricsAddress":":9998","authInternalUsers":[]}'
expect_state:
  config:
    log_level: info
    auth_method: internal
    rtsp: true
    rtmp: true
    hls: true
    webrtc: true
    srt: true
    moq: false
    playback: false
    metrics: true
    rtsp_address: :8554
    rtsps_address: :8322
    rtmp_address: :1935
    rtmps_address: :1936
    hls_address: :8888
    webrtc_address: :8889
    srt_address: :8890
    playback_address: :9996
    metrics_address: :9998
