spec: brompton-tessera
command: set_shuttersync_angle_settings_shutter_angle
input:
  shutter_angle: 360
expect_request:
  method: PUT
  target: /api/output/network/shuttersync/angle-settings/shutter-angle
  body: '{"data":360.000}'
