spec: barco-eventmaster
command: configure_operator
input:
  params:
    operatorId: 1
    add:
      destType: 1
      destIndex: 0
    remove:
      destType: 1
      destIndex: 1
expect_request:
  method: POST
  target: /
  body: '{"params":{"operatorId":1,"add":{"destType":1,"destIndex":0},"remove":{"destType":1,"destIndex":1}},"method":"configureOperator","id":"1234","jsonrpc":"2.0"}'
