RV = "roland-v160hd"
# Roland V-160HD / V-80HD / VR-120HD / VR-6HD / V-1-4K. Wire forms written by
# hand from "LAN/RS-232 Basic Control Commands" edition 02 (page numbers
# below) and the Remote Control Guides: "Command code:parameter,parameter;"
# (p.2), sent without stx over LAN and ended CR LF as a Telnet client does.
# Replies end in ACK; or ERR:n;, each frame followed by LF (p.2).
RV_OK = {"ok": {"kind": "ack"}}
RV_ERR = {"error": {"error": "device_error"}}


def rv(command, input, wire, **extra):
    text(RV, command, input, wire, **extra)


# VIDEO (p.3-19); the document's own examples where it gives them.
rv("get_video_input_source", {"index": 0}, "QVISRC:0;\r\n",
   device_reply="VISRC:0,HDMI1;\nACK;\n", expect_result=RV_OK)          # p.3 example
rv("get_video_input_status", {"input": "HDMI1"}, "QVIST:HDMI1;\r\n",
   device_reply="VIST:HDMI1,DETECTED;\nACK;\n", expect_result=RV_OK)    # p.3 example
rv("set_video_fader_level", {"level": 1024}, "VFL:1024;\r\n",
   device_reply="ACK;\n", expect_result=RV_OK)                          # p.4 example
rv("get_video_fader_level", {}, "QVFL;\r\n",
   device_reply="VFL:1024;ACK;\n", expect_result=RV_OK)                 # p.4 example, one line
rv("select_pgm", {"source": "INPUT2"}, "PGM:INPUT2;\r\n",
   device_reply="\x02ACK;\n", expect_result=RV_OK)                      # p.4 example, with stx
rv("get_pgm", {}, "QPGM;\r\n", device_reply="PGM:HDMI2,INPUT2;\nACK;\n", expect_result=RV_OK)   # p.5 example
rv("select_pst", {"source": "SDI3"}, "PST:SDI3;\r\n", device_reply="ERR:5;\n", expect_result=RV_ERR)
rv("get_pst", {}, "QPST;\r\n")
rv("select_aux", {"aux": 2, "source": "PGMLINK"}, "AUX:AUX2,PGMLINK;\r\n")
rv("get_aux", {"aux": 1}, "QAUX:AUX1;\r\n")
rv("auto", {}, "ATO;\r\n", device_reply="ERR:4;\n", expect_result=RV_ERR)
rv("auto_to", {"source": "V.PLAYER"}, "ATO:V.PLAYER;\r\n")
rv("auto_to_with_time", {"source": "INPUT1", "time": 10}, "ATO:INPUT1,10;\r\n")      # p.7 example
rv("cut", {}, "CUT;\r\n", device_reply="ACK;\n", expect_result=RV_OK)
rv("cut_to", {"source": "HDMI8"}, "CUT:HDMI8;\r\n")
rv("get_auto_transition", {}, "QATG;\r\n", device_reply="ATG:ON;\nACK;\n", expect_result=RV_OK)  # p.7 example
rv("toggle_freeze", {}, "FRZ;\r\n")
rv("set_freeze", {"enabled": True}, "FRZ:ON;\r\n")
rv("get_freeze", {}, "QFRZ;\r\n")
rv("toggle_output_fade", {}, "FTB;\r\n")
rv("set_output_fade", {"enabled": False}, "FTB:OFF;\r\n")
rv("get_output_fade", {}, "QFTB;\r\n")
rv("set_input_assign", {"input": 1, "source": "HDMI1"}, "VIS:INPUT1,HDMI1;\r\n")    # p.8 example
rv("get_input_assign", {"input": 1}, "QVIS:INPUT1;\r\n",
   device_reply="VIS:INPUT1,HDMI1;\nACK;\n", expect_result=RV_OK)                   # p.9 example
rv("set_output_assign", {"output": "HDMI2", "bus": "MULTIVIEW"}, "VOS:HDMI2,MULTIVIEW;\r\n")
rv("get_output_assign", {"output": "USB"}, "QVOS:USB;\r\n")
rv("set_transition_type", {"type": "WIPE"}, "TRS:WIPE;\r\n")
rv("get_transition_type", {}, "QTRS;\r\n")
rv("set_transition_time", {"target": "MIX", "time": 10}, "TIM:MIX,10;\r\n")          # p.10 example
rv("get_transition_time", {"target": "MIX"}, "QTIM:MIX;\r\n",
   device_reply="TIM:MIX,10;\nACK;\n", expect_result=RV_OK)                         # p.11 example
rv("set_pinp_source", {"pinp": 3, "source": "STILL5"}, "PIS:PinP3,STILL5;\r\n")
rv("get_pinp_source", {"pinp": 1}, "QPIS:PinP1;\r\n")
rv("toggle_pinp_pgm", {"pinp": 2}, "PPS:PinP2;\r\n")
rv("set_pinp_pgm", {"pinp": 1, "enabled": True}, "PPS:PinP1,ON;\r\n")
rv("get_pinp_pgm", {"pinp": 4}, "QPPS:PinP4;\r\n")
rv("toggle_pinp_pvw", {"pinp": 1}, "PPW:PinP1;\r\n")
rv("set_pinp_pvw", {"pinp": 2, "enabled": False}, "PPW:PinP2,OFF;\r\n")
rv("get_pinp_pvw", {"pinp": 2}, "QPPW:PinP2;\r\n")
rv("set_pinp_position", {"pinp": 1, "h": -500, "v": 250}, "PIP:PinP1,-500,250;\r\n")
rv("get_pinp_position", {"pinp": 1}, "QPIP:PinP1;\r\n")
rv("toggle_dsk_pgm", {"dsk": 1}, "DSK:DSK1;\r\n")
rv("set_dsk_pgm", {"dsk": 2, "enabled": True}, "DSK:DSK2,ON;\r\n")
rv("get_dsk_pgm", {"dsk": 1}, "QDSK:DSK1;\r\n")
rv("toggle_dsk_pvw", {"dsk": 1}, "DVW:DSK1;\r\n")
rv("set_dsk_pvw", {"dsk": 1, "enabled": False}, "DVW:DSK1,OFF;\r\n")
rv("get_dsk_pvw", {"dsk": 2}, "QDVW:DSK2;\r\n")
rv("set_dsk_source", {"dsk": 1, "source": "STILL16"}, "DSS:DSK1,STILL16;\r\n")
rv("get_dsk_source", {"dsk": 1}, "QDSS:DSK1;\r\n")
rv("set_dsk_level", {"dsk": 1, "level": 255}, "KYL:DSK1,255;\r\n")
rv("get_dsk_level", {"dsk": 1}, "QKYL:DSK1;\r\n")
rv("set_dsk_gain", {"dsk": 2, "gain": 0}, "KYG:DSK2,0;\r\n")
rv("get_dsk_gain", {"dsk": 2}, "QKYG:DSK2;\r\n")
rv("toggle_split", {"split": 1}, "SPS:SPLIT1;\r\n")
rv("set_split", {"split": 2, "enabled": True}, "SPS:SPLIT2,ON;\r\n")
rv("get_split", {"split": 1}, "QSPS:SPLIT1;\r\n")
rv("set_split_centers", {"split": 1, "a_center": -250, "b_center": 250}, "SPT:SPLIT1,-250,250;\r\n")
rv("set_split_positions", {"split": 1, "a_center": 0, "b_center": 0, "center": -500}, "SPT:SPLIT1,0,0,-500;\r\n")
rv("get_split_positions", {"split": 2}, "QSPT:SPLIT2;\r\n")
rv("set_still_output", {"source": "OFF"}, "STO:OFF;\r\n")
rv("get_still_output", {}, "QSTO;\r\n")
rv("set_roi_mode", {"enabled": True}, "ROISW:ON;\r\n", model="v-1-4k")
rv("get_roi_mode", {}, "QROISW;\r\n", model="v-1-4k")
rv("set_roi_zoom", {"roi": 2, "zoom": 2000}, "ROIZM:ROI2,2000;\r\n", model="v-1-4k")
rv("get_roi_zoom", {"roi": 2}, "QROIZM:ROI2;\r\n", model="v-1-4k")
rv("set_roi_position", {"roi": 4, "h": -1920, "v": 1080}, "ROIPT:ROI4,-1920,1080;\r\n", model="v-1-4k")
rv("get_roi_position", {"roi": 4}, "QROIPT:ROI4;\r\n", model="v-1-4k")

# AUDIO (p.20-27)
rv("set_audio_output_assign", {"output": "HDMI1", "bus": "AUTO"}, "AOS:HDMI1,AUTO;\r\n")
rv("get_audio_output_assign", {"output": "PHONES"}, "QAOS:PHONES;\r\n")
rv("set_input_level", {"input": "XLR1", "level": -60}, "IAL:XLR1,-60;\r\n",
   device_reply="ACK;\n", expect_result=RV_OK)                                       # p.21 example
rv("set_input_level_inf", {"input": "HDMI3"}, "IAL:HDMI3,-INF;\r\n")
rv("get_input_level", {"input": "XLR1"}, "QIAL:XLR1;\r\n",
   device_reply="IAL:XLR1,-60;\nACK;\n", expect_result=RV_OK)                       # p.22 example
rv("toggle_input_mute", {"input": "USB"}, "IAM:USB;\r\n")
rv("set_input_mute", {"input": "BLUETOOTH", "enabled": True}, "IAM:BLUETOOTH,ON;\r\n")
rv("get_input_mute", {"input": "SDI1"}, "QIAM:SDI1;\r\n")
rv("toggle_input_solo", {"input": "RCA1"}, "IAS:RCA1;\r\n")
rv("set_input_solo", {"input": "XLR2", "enabled": False}, "IAS:XLR2,OFF;\r\n")
rv("get_input_solo", {"input": "XLR2"}, "QIAS:XLR2;\r\n")
rv("set_input_delay", {"input": "HDMI1", "delay": 5000}, "ADT:HDMI1,5000;\r\n")
rv("get_input_delay", {"input": "HDMI1"}, "QADT:HDMI1;\r\n")
rv("set_high_pass_filter", {"input": "XLR1", "enabled": True}, "HPF:XLR1,ON;\r\n")
rv("get_high_pass_filter", {"input": "XLR1"}, "QHPF:XLR1;\r\n")
rv("set_gate", {"input": "XLR2", "enabled": True}, "GATE:XLR2,ON;\r\n")
rv("get_gate", {"input": "XLR2"}, "QGATE:XLR2;\r\n")
rv("toggle_stereo_link", {"xlr": 1}, "STLK:XLR1;\r\n")
rv("set_stereo_link", {"xlr": 1, "enabled": True}, "STLK:XLR1,ON;\r\n")
rv("get_stereo_link", {"xlr": 1}, "QSTLK:XLR1;\r\n")
rv("toggle_voice_changer", {"xlr": 2}, "VOCH:XLR2;\r\n")
rv("set_voice_changer", {"xlr": 1, "enabled": False}, "VOCH:XLR1,OFF;\r\n")
rv("get_voice_changer", {"xlr": 1}, "QVOCH:XLR1;\r\n")
rv("set_output_level", {"output": "MAIN", "level": 0}, "OAL:MAIN,0;\r\n")
rv("set_output_level_inf", {"output": "AUX3"}, "OAL:AUX3,-INF;\r\n")
rv("get_output_level", {"output": "MAIN"}, "QOAL:MAIN;\r\n")
rv("set_output_mute", {"output": "USB", "enabled": True}, "OAM:USB,ON;\r\n")
rv("get_output_mute", {"output": "USB"}, "QOAM:USB;\r\n")
rv("toggle_reverb", {}, "RVB;\r\n")
rv("set_reverb", {"enabled": True}, "RVB:ON;\r\n")
rv("get_reverb", {}, "QRVB;\r\n")
rv("toggle_auto_mixing", {}, "ATM;\r\n")
rv("set_auto_mixing", {"enabled": False}, "ATM:OFF;\r\n")
rv("get_auto_mixing", {}, "QATM;\r\n")

# METER (p.28-31)
rv("get_meter_levels", {"point": "PFL"}, "MTRLV:PFL;\r\n",
   device_reply="MTRLV:-INF,-80,10;\nACK;\n", expect_result=RV_OK)                   # p.28 example, shortened
rv("get_meter_channel", {"index": 0}, "MTRCH:0;\r\n",
   device_reply="MTRCH:0,IN-XLR1;\nACK;\n", expect_result=RV_OK)                    # p.28 example
rv("get_comp_gr_levels", {}, "GRLV;\r\n")
rv("get_comp_gr_channel", {"index": 2}, "GRCH:2;\r\n",
   device_reply="GRCH:2,IN-RCA1;\n", expect_result={"ok": {"kind": "value", "value": "IN-RCA1"}})
rv("get_auto_mixing_levels", {}, "AMLV;\r\n")
rv("get_auto_mixing_channel", {"index": 0}, "AMCH:0;\r\n",
   device_reply="\x02AMCH:0,IN-XLR1;\n", expect_result={"ok": {"kind": "value", "value": "IN-XLR1"}})
rv("get_sig_peak_levels", {}, "SPLV;\r\n")
rv("get_sig_peak_channel", {"index": 21}, "SPCH:21;\r\n",
   device_reply="SPCH:21,OUT-MAIN;\n", expect_result={"ok": {"kind": "value", "value": "OUT-MAIN"}})
rv("get_aux_levels", {"aux": 1}, "AUXLV:AUX1;\r\n")
rv("get_aux_channel", {"index": 1}, "AUXCH:1;\r\n",
   device_reply="QAUXCH:1,IN-XLR2;\n", expect_result={"ok": {"kind": "value", "value": "IN-XLR2"}})

# CONTROL (p.32-38)
rv("recall_memory", {"memory": 3}, "MEM:MEMORY3;\r\n")
rv("get_memory", {}, "QMEM;\r\n")
rv("pulse_gpo", {"gpo": 16}, "GPO:GPO16;\r\n")
rv("set_gpo", {"gpo": 1, "enabled": True}, "GPO:GPO1,ON;\r\n")
rv("get_gpo", {"gpo": 1}, "QGPO:GPO1;\r\n")
rv("get_tally", {}, "TLY;\r\n", device_reply="TLY:0,1,2,0;\nACK;\n", expect_result=RV_OK)   # p.33 example, shortened
rv("toggle_auto_switching", {}, "ASW;\r\n")
rv("set_auto_switching", {"enabled": True}, "ASW:ON;\r\n")
rv("get_auto_switching", {}, "QASW;\r\n")
rv("input_scan", {"mode": "RANDOM"}, "INSC:RANDOM;\r\n")
rv("memory_scan", {"mode": "NORMAL"}, "MEMSC:NORMAL;\r\n")
rv("pinp_source_scan", {"pinp": 2, "mode": "REVERSE"}, "PPSC:PinP2,REVERSE;\r\n")
rv("dsk_source_scan", {"dsk": 1, "mode": "NORMAL"}, "DSKSC:DSK1,NORMAL;\r\n")
rv("set_stream_record_type", {"type": "SRT"}, "STRTY:SRT;\r\n", model="v-80hd")
rv("get_stream_record_type", {}, "QSTRTY;\r\n", model="v-80hd")
rv("stream_record", {"action": "START"}, "STROA:START;\r\n", model="v-80hd")
rv("srt_out", {"action": "STOP"}, "SRTOSS:STOP;\r\n", model="vr-120hd")
rv("get_stream_record_status", {}, "QSTRST;\r\n", model="v-80hd")
rv("get_stream_record_time", {}, "QSTRTM;\r\n", model="v-80hd",
   device_reply="STRTM:30;\nACK;\n", expect_result=RV_OK)                          # p.35 example
rv("set_safety_image", {"enabled": True}, "SFIM:ON;\r\n", model="vr-6hd")
rv("get_safety_image", {}, "QSFIM;\r\n", model="vr-6hd")
rv("set_external_rec_control", {"enabled": True}, "EXRC:ON;\r\n", model="v-80hd")
rv("get_external_rec_control", {}, "QEXRC;\r\n", model="v-80hd")
rv("audio_player", {"pad": "A-1", "action": "PLAY"}, "APL:A-1,PLAY;\r\n", model="v-80hd")
rv("get_audio_player_status", {"pad": "H-8"}, "QAPS:H-8;\r\n", model="v-80hd")
rv("get_audio_player_import", {"pad": "B-2"}, "QAPE:B-2;\r\n", model="vr-120hd")
rv("get_audio_player_length", {"pad": "A-3"}, "QAPD:A-3;\r\n", model="vr-120hd")
rv("get_audio_player_time", {"pad": "A-3"}, "QAPC:A-3;\r\n", model="vr-120hd")
rv("set_audio_player_repeat", {"pad": "B-6", "enabled": True}, "APR:B-6,ON;\r\n", model="vr-6hd")
rv("get_audio_player_repeat", {"pad": "B-6"}, "QAPR:B-6;\r\n", model="vr-6hd")
rv("set_playback_type", {"type": "V.PLAYER"}, "PBTY:V.PLAYER;\r\n", model="v-80hd")
rv("get_playback_type", {}, "QPBTY;\r\n", model="v-80hd")
rv("video_player", {"action": "PAUSE"}, "VPL:PAUSE;\r\n", model="v-80hd")
rv("get_video_player_status", {}, "QVPS;\r\n", model="v-80hd")
rv("get_video_player_import", {}, "QVPE;\r\n", model="v-80hd")
rv("get_video_player_length", {}, "QVPD;\r\n", model="v-80hd")
rv("get_video_player_time", {}, "QVPC;\r\n", model="v-80hd")
rv("srt_in", {"action": "START"}, "SRTISS:START;\r\n", model="v-80hd")
rv("get_srt_in_status", {}, "QSRTIST;\r\n", model="v-80hd",
   device_reply="SRTIST:STARTED;\n", expect_result={"ok": {"kind": "value", "value": "STARTED"}})
rv("check_stream_record_ready", {}, "STRSTB;\r\n", model="v-80hd")
rv("check_video_player_ready", {}, "VPSTB;\r\n", model="v-80hd")
rv("check_srt_in_ready", {}, "SRTISTB;\r\n", model="v-80hd")

# CAMERA (p.39-41)
rv("camera_pan_tilt", {"camera": 1, "pan": "LEFT", "tilt": "STOP"}, "CAMPT:CAMERA1,LEFT,STOP;\r\n")
rv("set_camera_pan_tilt_speed", {"camera": 16, "speed": 24}, "CAMPTS:CAMERA16,24;\r\n")
rv("get_camera_pan_tilt_speed", {"camera": 16}, "QCAMPTS:CAMERA16;\r\n")
rv("camera_zoom", {"camera": 2, "zoom": "TELE_FAST"}, "CAMZM:CAMERA2,TELE_FAST;\r\n")
rv("camera_zoom_reset", {"camera": 2}, "CAMZMR:CAMERA2;\r\n")
rv("camera_focus", {"camera": 3, "focus": "NEAR"}, "CAMFC:CAMERA3,NEAR;\r\n")
rv("set_camera_auto_focus", {"camera": 3, "enabled": True}, "CAMAFC:CAMERA3,ON;\r\n")
rv("get_camera_auto_focus", {"camera": 3}, "QCAMAFC:CAMERA3;\r\n")
rv("set_camera_auto_exposure", {"camera": 4, "enabled": False}, "CAMAEP:CAMERA4,OFF;\r\n")
rv("get_camera_auto_exposure", {"camera": 4}, "QCAMAEP:CAMERA4;\r\n")
rv("camera_preset_recall", {"camera": 1, "preset": 100}, "CAMPR:CAMERA1,PRESET100;\r\n")
rv("get_camera_preset", {"camera": 1}, "QCAMPR:CAMERA1;\r\n")

# Macro, Sequencer, Graphics Presenter (p.42-43)
rv("execute_macro", {"macro": 12}, "MCREX:MACRO12;\r\n")
rv("get_macro_running", {"macro": 12}, "QMCRST:MACRO12;\r\n")
rv("set_sequencer", {"enabled": True}, "SEQSW:ON;\r\n")
rv("get_sequencer", {}, "QSEQSW;\r\n")
rv("set_auto_sequence", {"enabled": False}, "SEQAS:OFF;\r\n")
rv("get_auto_sequence", {}, "QSEQAS;\r\n")
rv("sequencer_previous", {}, "SEQPV;\r\n")
rv("sequencer_back", {"to_start": True}, "SEQPV:1;\r\n")
rv("sequencer_next", {}, "SEQNX;\r\n")
rv("sequencer_jump", {"sequence": 1000}, "SEQJP:SEQ1000;\r\n")
rv("sequencer_jump_start", {}, "SEQJP:START;\r\n")
rv("graphics_next", {}, "GPNC;\r\n")
rv("graphics_select", {"content": 124}, "GPSC:CONTENT124;\r\n")
rv("graphics_hide_front", {}, "GPHF;\r\n")
rv("graphics_hide_background", {}, "GPHB;\r\n")
rv("graphics_toggle_on_air", {}, "GPOA;\r\n")

# SYSTEM (p.44-45)
rv("active_sense", {}, "ACS;\r\n", device_reply="ACK;\n", expect_result=RV_OK)
rv("get_version", {}, "VER;\r\n", device_reply="VER:V-160HD,3.50;\nACK;\n", expect_result=RV_OK)
rv("get_busy", {}, "QBSY;\r\n", device_reply="BSY:OFF;\n", expect_result={"ok": {"kind": "value", "value": "OFF"}})
rv("set_hdcp", {"enabled": True}, "HDCP:ON;\r\n")
rv("get_hdcp", {}, "QHDCP;\r\n")
rv("set_test_pattern", {"pattern": "COLORBAR75-SP"}, "TPT:COLORBAR75-SP;\r\n")
rv("get_test_pattern", {}, "QTPT;\r\n")
rv("set_test_tone", {"level": "-20"}, "TTN:-20;\r\n")
rv("set_test_tone_frequency", {"level": "-10", "left": "1k", "right": "2k"}, "TTN:-10,1k,2k;\r\n")
rv("get_test_tone", {}, "QTTN;\r\n")

# Regular commands (V-160HD Remote Control Guide p.38: the document's example
# "DTH:123456,01;", and PGM Select at 00 21 00 from p.35)
rv("set_parameter", {"address": "123456", "value": "01"}, "DTH:123456,01;\r\n",
   device_reply="\x02ACK;\n", expect_result=RV_OK)
rv("get_parameter", {"address": "002100"}, "RQH:002100,000001;\r\n",
   device_reply="DTH:002100,21;\nACK;\n", expect_result=RV_OK)

# ── Telemetry: one vector per rule ────────────────────────────────────────
def rvt(name, inbound, state):
    telemetry(RV, name, inbound=inbound, expect_state=state)


rvt("video-input-source", "VISRC:0,HDMI1;\n", {"video_sources": {"0": {"name": "HDMI1"}}})
rvt("video-input-status", "VIST:HDMI1,DETECTED;\n", {"video_inputs": {"HDMI1": {"status": "DETECTED"}}})
rvt("fader-level", "VFL:1024;ACK;\n", {"fader": {"level": 1024}})
rvt("pgm-direct", "PGM:HDMI2;\n", {"program": {"source": "HDMI2", "input": ""}})
rvt("pgm-input", "\x02PGM:HDMI2,INPUT2;\n", {"program": {"source": "HDMI2", "input": "INPUT2"}})
rvt("pst-direct", "PST:STILL3;\n", {"preview": {"source": "STILL3", "input": ""}})
rvt("pst-input", "PST:SDI1,INPUT5;\n", {"preview": {"source": "SDI1", "input": "INPUT5"}})
rvt("aux-direct", "AUX:AUX2,SDI4;\n", {"aux": {"2": {"source": "SDI4", "input": ""}}})
rvt("aux-input", "AUX:AUX1,HDMI3,INPUT7;\n", {"aux": {"1": {"source": "HDMI3", "input": "INPUT7"}}})
rvt("auto-transition", "ATG:ON;\n", {"transition": {"auto_in_progress": True}})
rvt("freeze", "FRZ:OFF;\n", {"freeze": False})
rvt("output-fade", "FTB:FADEOUT;\n", {"output_fade": "FADEOUT"})
rvt("input-assign", "VIS:INPUT1,HDMI1;\n", {"input_assign": {"1": "HDMI1"}})
rvt("output-assign", "VOS:SDI2,AUX1;\n", {"video_outputs": {"SDI2": {"bus": "AUX1"}}})
rvt("transition-type", "TRS:WIPE;\n", {"transition": {"type": "WIPE"}})
rvt("transition-time", "TIM:MIX,10;\n", {"transition_time": {"MIX": 10}})
rvt("pinp-source", "PIS:PinP3,INPUT4;\n", {"pinp": {"3": {"source": "INPUT4"}}})
rvt("pinp-pgm", "PPS:PinP1,ON;\n", {"pinp": {"1": {"pgm": True}}})
rvt("pinp-pvw", "PPW:PinP2,OFF;\n", {"pinp": {"2": {"pvw": False}}})
rvt("pinp-position", "PIP:PinP1,-500,120;\n", {"pinp": {"1": {"position_h": -500, "position_v": 120}}})
rvt("dsk-pgm", "DSK:DSK1,ON;\n", {"dsk": {"1": {"pgm": True}}})
rvt("dsk-pvw", "DVW:DSK2,ON;\n", {"dsk": {"2": {"pvw": True}}})
rvt("dsk-source-input", "DSS:DSK1,STILL2,INPUT9;\n", {"dsk": {"1": {"source": "STILL2", "input": "INPUT9"}}})
rvt("dsk-source-direct", "DSS:DSK2,HDMI5;\n", {"dsk": {"2": {"source": "HDMI5", "input": ""}}})
rvt("dsk-level", "KYL:DSK1,128;\n", {"dsk": {"1": {"level": 128}}})
rvt("dsk-gain", "KYG:DSK1,64;\n", {"dsk": {"1": {"gain": 64}}})
rvt("split", "SPS:SPLIT2,ON;\n", {"split": {"2": {"on": True}}})
rvt("split-positions", "SPT:SPLIT1,-250,250,0;\n", {"split": {"1": {"a_center": -250, "b_center": 250, "center": 0}}})
rvt("still-output", "STO:STILL4;\n", {"still_output": "STILL4"})
rvt("roi-mode", "ROISW:ON;\n", {"roi": {"mode": True}})
rvt("roi-zoom", "ROIZM:ROI1,1500;\n", {"roi": {"1": {"zoom": 1500}}})
rvt("roi-position", "ROIPT:ROI2,-1920,540;\n", {"roi": {"2": {"position_h": -1920, "position_v": 540}}})
rvt("audio-output-assign", "AOS:HDMI1,AUTO;\n", {"audio_outputs": {"HDMI1": {"bus": "AUTO"}}})
rvt("input-level", "IAL:XLR1,-60;ACK;\n", {"audio_inputs": {"XLR1": {"level": "-60"}}})
rvt("input-level-inf", "IAL:HDMI2,-INF;\n", {"audio_inputs": {"HDMI2": {"level": "-INF"}}})
rvt("input-mute", "IAM:USB,ON;\n", {"audio_inputs": {"USB": {"mute": True}}})
rvt("input-solo", "IAS:XLR2,OFF;\n", {"audio_inputs": {"XLR2": {"solo": False}}})
rvt("input-delay", "ADT:SDI1,1200;\n", {"audio_inputs": {"SDI1": {"delay": 1200}}})
rvt("input-hpf", "HPF:XLR1,ON;\n", {"audio_inputs": {"XLR1": {"high_pass_filter": True}}})
rvt("input-gate", "GATE:XLR1,OFF;\n", {"audio_inputs": {"XLR1": {"gate": False}}})
rvt("stereo-link", "STLK:XLR1,ON;\n", {"audio_inputs": {"XLR1": {"stereo_link": True}}})
rvt("voice-changer", "VOCH:XLR2,ON;\n", {"audio_inputs": {"XLR2": {"voice_changer": True}}})
rvt("output-level", "OAL:MAIN,-INF;\n", {"audio_buses": {"MAIN": {"level": "-INF"}}})
rvt("output-mute", "OAM:AUX1,ON;\n", {"audio_buses": {"AUX1": {"mute": True}}})
rvt("reverb", "RVB:ON;\n", {"reverb": True})
rvt("auto-mixing", "ATM:OFF;\n", {"auto_mixing": False})
rvt("meter-levels", "MTRLV:-INF,-80,10;\n", {"meters": {"levels": "-INF,-80,10"}})
rvt("meter-channel", "MTRCH:0,IN-XLR1;\n", {"meters": {"channels": {"0": "IN-XLR1"}}})
rvt("gr-levels", "GRLV:-INF,-3;\n", {"meters": {"comp_gr_levels": "-INF,-3"}})
rvt("gr-channel", "GRCH:1,IN-XLR2;\n", {"meters": {"comp_gr_channels": {"1": "IN-XLR2"}}})
rvt("am-levels", "AMLV:-12,-INF;\n", {"meters": {"auto_mixing_levels": "-12,-INF"}})
rvt("am-channel", "AMCH:3,IN-USB;\n", {"meters": {"auto_mixing_channels": {"3": "IN-USB"}}})
rvt("sp-levels", "SPLV:0,-6;\n", {"meters": {"sig_peak_levels": "0,-6"}})
rvt("sp-channel", "SPCH:21,OUT-MAIN;\n", {"meters": {"sig_peak_channels": {"21": "OUT-MAIN"}}})
rvt("aux-levels", "QAUXLV:-20,-INF;\n", {"meters": {"aux_levels": "-20,-INF"}})
rvt("aux-channel", "QAUXCH:0,IN-XLR1;\n", {"meters": {"aux_channels": {"0": "IN-XLR1"}}})
rvt("memory", "MEM:MEMORY3;\n", {"memory": "MEMORY3"})
rvt("gpo", "GPO:GPO5,ON;\n", {"gpo": {"5": True}})
rvt("tally", "TLY:0,1,2,3,0;ACK;\n", {"tally": "0,1,2,3,0"})
rvt("auto-switching", "ASW:ON;\n", {"auto_switching": True})
rvt("stream-type", "STRTY:RTMP;\n", {"stream": {"type": "RTMP"}})
rvt("stream-status", "STRST:ONAIR;\n", {"stream": {"status": "ONAIR"}})
rvt("stream-time", "STRTM:30;\n", {"stream": {"elapsed": 30}})
rvt("safety-image", "SFIM:DELAYED;\n", {"stream": {"safety_image": "DELAYED"}})
rvt("external-rec", "EXRC:ON;\n", {"stream": {"external_rec_control": True}})
rvt("stream-ready", "STRSTB:ERROR_NO_SDCARD;\n", {"stream": {"ready": "ERROR_NO_SDCARD"}})
rvt("audio-player-status", "APS:A-1,PLAY;\n", {"audio_player": {"A-1": {"status": "PLAY"}}})
rvt("audio-player-import", "APE:B-2,ON;\n", {"audio_player": {"B-2": {"imported": True}}})
rvt("audio-player-length", "APD:A-1,180000;\n", {"audio_player": {"A-1": {"length": 180000}}})
rvt("audio-player-time", "APC:A-1,4500;\n", {"audio_player": {"A-1": {"position": 4500}}})
rvt("audio-player-repeat", "APR:H-8,OFF;\n", {"audio_player": {"H-8": {"repeat": False}}})
rvt("playback-type", "PBTY:V.PLAYER;\n", {"video_player": {"type": "V.PLAYER"}})
rvt("video-player-status", "VPS:PLAY;\n", {"video_player": {"status": "PLAY"}})
rvt("video-player-import", "VPE:SDCARD;\n", {"video_player": {"import": "SDCARD"}})
rvt("video-player-length", "VPD:60000;\n", {"video_player": {"length": 60000}})
rvt("video-player-time", "VPC:1000;\n", {"video_player": {"position": 1000}})
rvt("video-player-ready", "VPSTB:ERROR_NOT_FOUND;\n", {"video_player": {"ready": "ERROR_NOT_FOUND"}})
rvt("srt-in-status", "SRTIST:STARTING;\n", {"srt_in": {"status": "STARTING"}})
rvt("srt-in-ready", "SRTISTB:OK;\n", {"srt_in": {"ready": "OK"}})
rvt("camera-speed", "CPTS:CAMERA2,12;\n", {"cameras": {"2": {"pan_tilt_speed": 12}}})
rvt("camera-auto-focus", "CAFC:CAMERA1,ON;\n", {"cameras": {"1": {"auto_focus": True}}})
rvt("camera-auto-exposure", "CAEP:CAMERA1,OFF;\n", {"cameras": {"1": {"auto_exposure": False}}})
rvt("camera-preset", "CPR:CAMERA3,PRESET7;\n", {"cameras": {"3": {"preset": "PRESET7"}}})
rvt("macro-running", "MCRST:MACRO12,ON;\n", {"macros": {"12": {"running": True}}})
rvt("sequencer", "SQS:ON;\n", {"sequencer": {"on": True}})
rvt("auto-sequence", "SQA:OFF;\n", {"sequencer": {"auto_sequence": False}})
rvt("version", "VER:V-160HD,3.50;ACK;\n", {"device": {"model": "V-160HD", "version": "3.50"}})
rvt("busy", "BSY:ON;\n", {"busy": True})
rvt("hdcp", "HCP:OFF;\n", {"hdcp": False})
rvt("test-pattern", "TPT:COLORBAR100;\n", {"test_pattern": "COLORBAR100"})
rvt("test-tone", "TTN:-20,1k,1k;\n", {"test_tone": {"level": "-20", "frequency_l": "1k", "frequency_r": "1k"}})
rvt("parameter", "\x02DTH:0C0000,01;\n", {"parameters": {"0C0000": "01"}})
