S = "shure-p300"
# Generated with the spec from Shure's command-string documents (see the spec's sources).
text(S, "get_model", {}, "< GET MODEL >", device_reply="< REP MODEL {P300                            } >", expect_result={'ok': {'kind': 'value', 'value': 'P300'}})
text(S, "get_serial_number", {}, "< GET SERIAL_NUM >", device_reply="< REP SERIAL_NUM {3TA1234567                      } >", expect_result={'ok': {'kind': 'value', 'value': '3TA1234567'}})
text(S, "get_firmware", {}, "< GET FW_VER >", device_reply="< REP FW_VER {4.4.10            } >", expect_result={'ok': {'kind': 'value', 'value': '4.4.10'}})
text(S, "get_device_id", {}, "< GET DEVICE_ID >", device_reply="< REP DEVICE_ID {Room 101                       } >", expect_result={'ok': {'kind': 'value', 'value': 'Room 101'}})
text(S, "get_ip_address", {}, "< GET IP_ADDR_NET_AUDIO_PRIMARY >", device_reply="< REP IP_ADDR_NET_AUDIO_PRIMARY {192.168.1.20   } >", expect_result={'ok': {'kind': 'value', 'value': '192.168.1.20'}})
text(S, "get_subnet", {}, "< GET IP_SUBNET_NET_AUDIO_PRIMARY >", device_reply="< REP IP_SUBNET_NET_AUDIO_PRIMARY {255.255.255.0  } >", expect_result={'ok': {'kind': 'value', 'value': '255.255.255.0'}})
text(S, "get_gateway", {}, "< GET IP_GATEWAY_NET_AUDIO_PRIMARY >", device_reply="< REP IP_GATEWAY_NET_AUDIO_PRIMARY {192.168.1.1    } >", expect_result={'ok': {'kind': 'value', 'value': '192.168.1.1'}})
text(S, "get_na_device_name", {}, "< GET NA_DEVICE_NAME >", device_reply="< REP NA_DEVICE_NAME {P300-ab12cd                    } >", expect_result={'ok': {'kind': 'value', 'value': 'P300-ab12cd'}})
text(S, "get_mac_address", {}, "< GET CONTROL_MAC_ADDR >", device_reply="< REP CONTROL_MAC_ADDR 00:0E:DD:FF:F1:63 >", expect_result={'ok': {'kind': 'value', 'value': '00:0E:DD:FF:F1:63'}})
text(S, "get_encryption", {}, "< GET ENCRYPTION >", device_reply="< REP ENCRYPTION ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_usb_connected", {}, "< GET USB_CONNECT >", device_reply="< REP USB_CONNECT ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_preset", {}, "< GET PRESET >", device_reply="< REP PRESET 03 >", expect_result={'ok': {'kind': 'value', 'value': '03'}})
text(S, "recall_preset", {'preset': 3}, "< SET PRESET 03 >", device_reply="< REP PRESET 03 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "recall_preset", {'preset': 10}, "< SET PRESET 10 >", device_reply="< REP ERR >", expect_result={'error': {'error': 'device_error'}})
text(S, "get_preset_name", {'preset': 2}, "< GET PRESET2 >", device_reply="< REP PRESET2 {Lecture                  } >", expect_result={'ok': {'kind': 'value', 'value': 'Lecture'}})
text(S, "flash", {'enabled': True}, "< SET FLASH ON >", device_reply="< REP FLASH ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "reboot", {}, "< SET REBOOT >", expect_result={'ok': {'kind': 'unverified'}})
text(S, "restore_defaults", {}, "< SET DEFAULT_SETTINGS >", device_reply="< REP DEFAULT_SETTINGS 00 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_all", {'channel': 0}, "< GET 00 ALL >", expect_result={'ok': {'kind': 'unverified'}})
text(S, "get_parameter", {'channel': 1, 'parameter': 'AUDIO_MUTE'}, "< GET 01 AUDIO_MUTE >", device_reply="< REP 01 AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'value', 'value': 'OFF'}})
text(S, "set_parameter", {'channel': 1, 'parameter': 'AUDIO_MUTE', 'value': 'ON'}, "< SET 01 AUDIO_MUTE ON >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_device_parameter", {'parameter': 'ENCRYPTION'}, "< GET ENCRYPTION >", device_reply="< REP ENCRYPTION OFF >", expect_result={'ok': {'kind': 'value', 'value': 'OFF'}})
text(S, "set_device_parameter", {'parameter': 'LED_BRIGHTNESS', 'value': '2'}, "< SET LED_BRIGHTNESS 2 >", device_reply="< REP LED_BRIGHTNESS 2 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_name", {'channel': 1}, "< GET 01 CHAN_NAME >", device_reply="< REP 01 CHAN_NAME {Podium                         } >", expect_result={'ok': {'kind': 'value', 'value': 'Podium'}})
text(S, "get_mute", {'channel': 1}, "< GET 01 AUDIO_MUTE >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_mute", {'channel': 1, 'muted': True}, "< SET 01 AUDIO_MUTE ON >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_mute", {'channel': 1}, "< SET 01 AUDIO_MUTE TOGGLE >", device_reply="< REP 01 AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_gain", {'channel': 1}, "< GET 01 AUDIO_GAIN_HI_RES >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'value', 'value': '1040'}})
text(S, "set_gain", {'channel': 1, 'gain_tenth_db': -60}, "< SET 01 AUDIO_GAIN_HI_RES 1040 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "increase_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN_HI_RES INC 10 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "decrease_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN_HI_RES DEC 10 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_device_mute", {}, "< GET DEVICE_AUDIO_MUTE >", device_reply="< REP DEVICE_AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_device_mute", {'muted': True}, "< SET DEVICE_AUDIO_MUTE ON >", device_reply="< REP DEVICE_AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_device_mute", {}, "< SET DEVICE_AUDIO_MUTE TOGGLE >", device_reply="< REP DEVICE_AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_input_level", {'channel': 11}, "< GET 11 AUDIO_IN_LVL_SWITCH >", device_reply="< REP 11 AUDIO_IN_LVL_SWITCH LINE_LVL >", expect_result={'ok': {'kind': 'value', 'value': 'LINE_LVL'}})
text(S, "set_input_level", {'channel': 11, 'value': 'AUX_LVL'}, "< SET 11 AUDIO_IN_LVL_SWITCH AUX_LVL >", device_reply="< REP 11 AUDIO_IN_LVL_SWITCH AUX_LVL >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_output_level", {'channel': 17}, "< GET 17 AUDIO_OUT_LVL_SWITCH >", device_reply="< REP 17 AUDIO_OUT_LVL_SWITCH LINE_LVL >", expect_result={'ok': {'kind': 'value', 'value': 'LINE_LVL'}})
text(S, "set_output_level", {'channel': 17, 'value': 'MIC_LVL'}, "< SET 17 AUDIO_OUT_LVL_SWITCH MIC_LVL >", device_reply="< REP 17 AUDIO_OUT_LVL_SWITCH MIC_LVL >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_led_brightness", {}, "< GET LED_BRIGHTNESS >", device_reply="< REP LED_BRIGHTNESS 2 >", expect_result={'ok': {'kind': 'value', 'value': '2'}})
text(S, "set_led_brightness", {'value': 2}, "< SET LED_BRIGHTNESS 2 >", device_reply="< REP LED_BRIGHTNESS 2 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_input_meter_mode", {}, "< GET INPUT_METER_MODE >", device_reply="< REP INPUT_METER_MODE PRE_FADER >", expect_result={'ok': {'kind': 'value', 'value': 'PRE_FADER'}})
text(S, "set_input_meter_mode", {'value': 'POST_FADER'}, "< SET INPUT_METER_MODE POST_FADER >", device_reply="< REP INPUT_METER_MODE POST_FADER >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_output_meter_mode", {}, "< GET OUTPUT_METER_MODE >", device_reply="< REP OUTPUT_METER_MODE PRE_FADER >", expect_result={'ok': {'kind': 'value', 'value': 'PRE_FADER'}})
text(S, "set_output_meter_mode", {'value': 'POST_FADER'}, "< SET OUTPUT_METER_MODE POST_FADER >", device_reply="< REP OUTPUT_METER_MODE POST_FADER >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate_in", {}, "< GET METER_RATE_IN >", device_reply="< REP METER_RATE_IN 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate_in", {'rate_ms': 1000}, "< SET METER_RATE_IN 01000 >", device_reply="< REP METER_RATE_IN 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate_out", {}, "< GET METER_RATE_OUT >", device_reply="< REP METER_RATE_OUT 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate_out", {'rate_ms': 1000}, "< SET METER_RATE_OUT 01000 >", device_reply="< REP METER_RATE_OUT 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate_proc", {}, "< GET METER_RATE_PROC >", device_reply="< REP METER_RATE_PROC 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate_proc", {'rate_ms': 1000}, "< SET METER_RATE_PROC 01000 >", device_reply="< REP METER_RATE_PROC 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate_erle", {}, "< GET METER_RATE_ERLE >", device_reply="< REP METER_RATE_ERLE 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate_erle", {'rate_ms': 1000}, "< SET METER_RATE_ERLE 01000 >", device_reply="< REP METER_RATE_ERLE 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate_agc", {}, "< GET METER_RATE_AGC >", device_reply="< REP METER_RATE_AGC 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate_agc", {'rate_ms': 1000}, "< SET METER_RATE_AGC 01000 >", device_reply="< REP METER_RATE_AGC 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_aec", {'channel': 1}, "< GET 01 AEC >", device_reply="< REP 01 AEC ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_aec", {'channel': 1, 'enabled': True}, "< SET 01 AEC ON >", device_reply="< REP 01 AEC ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_aec", {'channel': 1}, "< SET 01 AEC TOGGLE >", device_reply="< REP 01 AEC OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_aec_reference", {'channel': 22}, "< GET 22 AEC_REF >", device_reply="< REP 22 AEC_REF DANTEOUT1 >", expect_result={'ok': {'kind': 'value', 'value': 'DANTEOUT1'}})
text(S, "set_aec_reference", {'channel': 22, 'value': 'MOBILEIN'}, "< SET 22 AEC_REF MOBILEIN >", device_reply="< REP 22 AEC_REF MOBILEIN >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_aec_nlp", {'channel': 1}, "< GET 01 AEC_NLP >", device_reply="< REP 01 AEC_NLP MEDIUM >", expect_result={'ok': {'kind': 'value', 'value': 'MEDIUM'}})
text(S, "set_aec_nlp", {'channel': 1, 'value': 'HIGH'}, "< SET 01 AEC_NLP HIGH >", device_reply="< REP 01 AEC_NLP HIGH >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_noise_reduction", {'channel': 1}, "< GET 01 NOISE_RED >", device_reply="< REP 01 NOISE_RED ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_noise_reduction", {'channel': 1, 'enabled': True}, "< SET 01 NOISE_RED ON >", device_reply="< REP 01 NOISE_RED ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_noise_reduction_level", {'channel': 1}, "< GET 01 NOISE_RED_LVL >", device_reply="< REP 01 NOISE_RED_LVL LOW >", expect_result={'ok': {'kind': 'value', 'value': 'LOW'}})
text(S, "set_noise_reduction_level", {'channel': 1, 'value': 'HIGH'}, "< SET 01 NOISE_RED_LVL HIGH >", device_reply="< REP 01 NOISE_RED_LVL HIGH >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_agc", {'channel': 1}, "< GET 01 AGC >", device_reply="< REP 01 AGC ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_agc", {'channel': 1, 'enabled': True}, "< SET 01 AGC ON >", device_reply="< REP 01 AGC ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_agc", {'channel': 1}, "< SET 01 AGC TOGGLE >", device_reply="< REP 01 AGC OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_agc_max_cut", {'channel': 1}, "< GET 01 AGC_MAX_CUT >", device_reply="< REP 01 AGC_MAX_CUT 077 >", expect_result={'ok': {'kind': 'value', 'value': '077'}})
text(S, "set_agc_max_cut", {'channel': 1, 'cut_tenth_db': -123}, "< SET 01 AGC_MAX_CUT 077 >", device_reply="< REP 01 AGC_MAX_CUT 077 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_agc_max_boost", {'channel': 1}, "< GET 01 AGC_MAX_BOOST >", device_reply="< REP 01 AGC_MAX_BOOST 123 >", expect_result={'ok': {'kind': 'value', 'value': '123'}})
text(S, "set_agc_max_boost", {'channel': 1, 'boost_tenth_db': 123}, "< SET 01 AGC_MAX_BOOST 123 >", device_reply="< REP 01 AGC_MAX_BOOST 123 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_agc_target", {'channel': 1}, "< GET 01 AGC_TARGET >", device_reply="< REP 01 AGC_TARGET 377 >", expect_result={'ok': {'kind': 'value', 'value': '377'}})
text(S, "set_agc_target", {'channel': 1, 'target_tenth_dbfs': -123}, "< SET 01 AGC_TARGET 377 >", device_reply="< REP 01 AGC_TARGET 377 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_gate_inhibit", {'channel': 22}, "< GET 22 GATE_INHIBIT >", device_reply="< REP 22 GATE_INHIBIT ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_gate_inhibit", {'channel': 22, 'enabled': True}, "< SET 22 GATE_INHIBIT ON >", device_reply="< REP 22 GATE_INHIBIT ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_gate_inhibit", {'channel': 22}, "< SET 22 GATE_INHIBIT TOGGLE >", device_reply="< REP 22 GATE_INHIBIT OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_mode", {'channel': 21}, "< GET 21 AUTOMXR_MODE >", device_reply="< REP 21 AUTOMXR_MODE GATING >", expect_result={'ok': {'kind': 'value', 'value': 'GATING'}})
text(S, "set_automixer_mode", {'channel': 21, 'value': 'GATING'}, "< SET 21 AUTOMXR_MODE GATING >", device_reply="< REP 21 AUTOMXR_MODE GATING >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_off_attenuation", {'channel': 21}, "< GET 21 AUTOMXR_OFF_ATT >", device_reply="< REP 21 AUTOMXR_OFF_ATT 100 >", expect_result={'ok': {'kind': 'value', 'value': '100'}})
text(S, "set_automixer_off_attenuation", {'channel': 21, 'attenuation_db': -10}, "< SET 21 AUTOMXR_OFF_ATT 100 >", device_reply="< REP 21 AUTOMXR_OFF_ATT 100 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_gate_sensitivity", {'channel': 21}, "< GET 21 AUTOMXR_GATE_SEN >", device_reply="< REP 21 AUTOMXR_GATE_SEN 5 >", expect_result={'ok': {'kind': 'value', 'value': '5'}})
text(S, "set_automixer_gate_sensitivity", {'channel': 21, 'value': 9}, "< SET 21 AUTOMXR_GATE_SEN 9 >", device_reply="< REP 21 AUTOMXR_GATE_SEN 9 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_max_open", {'channel': 21}, "< GET 21 AUTOMXR_MAX_NOM >", device_reply="< REP 21 AUTOMXR_MAX_NOM 4 >", expect_result={'ok': {'kind': 'value', 'value': '4'}})
text(S, "set_automixer_max_open", {'channel': 21, 'value': 8}, "< SET 21 AUTOMXR_MAX_NOM 8 >", device_reply="< REP 21 AUTOMXR_MAX_NOM 8 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_last_mic_lock", {'channel': 21}, "< GET 21 AUTOMXR_LMLO >", device_reply="< REP 21 AUTOMXR_LMLO ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_automixer_last_mic_lock", {'channel': 21, 'enabled': True}, "< SET 21 AUTOMXR_LMLO ON >", device_reply="< REP 21 AUTOMXR_LMLO ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_automixer_last_mic_lock", {'channel': 21}, "< SET 21 AUTOMXR_LMLO TOGGLE >", device_reply="< REP 21 AUTOMXR_LMLO OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_hold_time", {'channel': 21}, "< GET 21 AUTOMXR_HOLDTIME >", device_reply="< REP 21 AUTOMXR_HOLDTIME 0400 >", expect_result={'ok': {'kind': 'value', 'value': '0400'}})
text(S, "set_automixer_hold_time", {'channel': 21, 'value': 1500}, "< SET 21 AUTOMXR_HOLDTIME 1500 >", device_reply="< REP 21 AUTOMXR_HOLDTIME 1500 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_always_on", {'channel': 1}, "< GET 01 AUTOMXR_ALWAYS_ON >", device_reply="< REP 01 AUTOMXR_ALWAYS_ON ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_automixer_always_on", {'channel': 1, 'enabled': True}, "< SET 01 AUTOMXR_ALWAYS_ON ON >", device_reply="< REP 01 AUTOMXR_ALWAYS_ON ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_automixer_always_on", {'channel': 1}, "< SET 01 AUTOMXR_ALWAYS_ON TOGGLE >", device_reply="< REP 01 AUTOMXR_ALWAYS_ON OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_priority", {'channel': 1}, "< GET 01 AUTOMXR_PRIORITY >", device_reply="< REP 01 AUTOMXR_PRIORITY ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_automixer_priority", {'channel': 1, 'enabled': True}, "< SET 01 AUTOMXR_PRIORITY ON >", device_reply="< REP 01 AUTOMXR_PRIORITY ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_automixer_priority", {'channel': 1}, "< SET 01 AUTOMXR_PRIORITY TOGGLE >", device_reply="< REP 01 AUTOMXR_PRIORITY OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_mute", {'channel': 21}, "< GET 21 AUTOMXR_MUTE >", device_reply="< REP 21 AUTOMXR_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_automixer_mute", {'channel': 21, 'muted': True}, "< SET 21 AUTOMXR_MUTE ON >", device_reply="< REP 21 AUTOMXR_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_automixer_mute", {'channel': 21}, "< SET 21 AUTOMXR_MUTE TOGGLE >", device_reply="< REP 21 AUTOMXR_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_gate", {'channel': 1}, "< GET 01 AUTOMXR_GATE >", device_reply="< REP 01 AUTOMXR_GATE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_compressor", {'channel': 21}, "< GET 21 COMPRESSOR >", device_reply="< REP 21 COMPRESSOR ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_compressor", {'channel': 21, 'enabled': True}, "< SET 21 COMPRESSOR ON >", device_reply="< REP 21 COMPRESSOR ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_compressor", {'channel': 21}, "< SET 21 COMPRESSOR TOGGLE >", device_reply="< REP 21 COMPRESSOR OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_compressor_threshold", {'channel': 21}, "< GET 21 COMP_THRESHOLD >", device_reply="< REP 21 COMP_THRESHOLD 477 >", expect_result={'ok': {'kind': 'value', 'value': '477'}})
text(S, "set_compressor_threshold", {'channel': 21, 'threshold_tenth_db': -123}, "< SET 21 COMP_THRESHOLD 477 >", device_reply="< REP 21 COMP_THRESHOLD 477 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_compressor_ratio", {'channel': 21}, "< GET 21 COMP_RATIO >", device_reply="< REP 21 COMP_RATIO 0123 >", expect_result={'ok': {'kind': 'value', 'value': '0123'}})
text(S, "set_compressor_ratio", {'channel': 21, 'ratio_tenths': 123}, "< SET 21 COMP_RATIO 0123 >", device_reply="< REP 21 COMP_RATIO 0123 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_delay", {'channel': 17}, "< GET 17 DELAY >", device_reply="< REP 17 DELAY 0010 >", expect_result={'ok': {'kind': 'value', 'value': '0010'}})
text(S, "set_delay", {'channel': 17, 'value': 1000}, "< SET 17 DELAY 1000 >", device_reply="< REP 17 DELAY 1000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_direct_out_point", {'channel': 1}, "< GET 01 DIRECTOUT_POINT >", device_reply="< REP 01 DIRECTOUT_POINT 3 >", expect_result={'ok': {'kind': 'value', 'value': '3'}})
text(S, "set_direct_out_point", {'channel': 1, 'value': 3}, "< SET 01 DIRECTOUT_POINT 3 >", device_reply="< REP 01 DIRECTOUT_POINT 3 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_call_status_enabled", {}, "< GET ONHOOK_ENABLE >", device_reply="< REP ONHOOK_ENABLE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_call_status_enabled", {'enabled': True}, "< SET ONHOOK_ENABLE ON >", device_reply="< REP ONHOOK_ENABLE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_call_state", {}, "< GET ONHOOK_STATE >", device_reply="< REP ONHOOK_STATE OFFHOOK >", expect_result={'ok': {'kind': 'value', 'value': 'OFFHOOK'}})
text(S, "get_matrix_route", {'input': 1, 'output': 15}, "< GET 01 MATRIX_MXR_ROUTE 15 >", device_reply="< REP 01 MATRIX_MXR_ROUTE 15 ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_matrix_route", {'input': 1, 'output': 15, 'enabled': False}, "< SET 01 MATRIX_MXR_ROUTE 15 OFF >", device_reply="< REP 01 MATRIX_MXR_ROUTE 15 OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "set_matrix_gain", {'input': 21, 'output': 17, 'gain_tenth_db': -35}, "< SET 21 MATRIX_MXR_GAIN 17 1065 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1065 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_matrix_gain", {'input': 21, 'output': 17}, "< GET 21 MATRIX_MXR_GAIN 17 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1100 >", expect_result={'ok': {'kind': 'value', 'value': 0.0}})
text(S, "increase_matrix_gain", {'input': 21, 'output': 17, 'step': 25}, "< SET 21 MATRIX_MXR_GAIN 17 INC 25 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1125 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "decrease_matrix_gain", {'input': 21, 'output': 17, 'step': 25}, "< SET 21 MATRIX_MXR_GAIN 17 DEC 25 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1125 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_peq_filter", {'block': 1, 'filter': 2}, "< GET 01 PEQ 02 >", device_reply="< REP 01 PEQ 02 ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_peq_filter", {'block': 1, 'filter': 2, 'state': 'OFF'}, "< SET 01 PEQ 02 OFF >", device_reply="< REP 01 PEQ 02 OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_mute", {'channel': 2}, "< GET 02 AUDIO_MUTE >", device_reply="< REP ERR >", expect_result={'error': {'error': 'device_error'}})
telemetry(S, "mute-gain-name", inbound="< REP 01 AUDIO_MUTE ON >< REP 01 AUDIO_GAIN_HI_RES 1040 >< REP 01 CHAN_NAME {Podium     } >< REP PRESET 03 >", expect_state={'channels': {'1': {'mute': True, 'gain': -6.0, 'name': 'Podium'}}, 'device': {'preset': 3}})
