S = "shure-mxn5"
# Generated with the spec from Shure's command-string documents (see the spec's sources).
text(S, "get_model", {}, "< GET MODEL >", device_reply="< REP MODEL {P300                            } >", expect_result={'ok': {'kind': 'value', 'value': 'P300'}})
text(S, "get_serial_number", {}, "< GET SERIAL_NUM >", device_reply="< REP SERIAL_NUM {3TA1234567                      } >", expect_result={'ok': {'kind': 'value', 'value': '3TA1234567'}})
text(S, "get_firmware", {}, "< GET FW_VER >", device_reply="< REP FW_VER {4.4.10            } >", expect_result={'ok': {'kind': 'value', 'value': '4.4.10'}})
text(S, "get_device_id", {}, "< GET DEVICE_ID >", device_reply="< REP DEVICE_ID {Room 101                       } >", expect_result={'ok': {'kind': 'value', 'value': 'Room 101'}})
text(S, "get_ip_address", {}, "< GET IP_ADDR_NET_AUDIO_PRIMARY >", device_reply="< REP IP_ADDR_NET_AUDIO_PRIMARY {192.168.1.20   } >", expect_result={'ok': {'kind': 'value', 'value': '192.168.1.20'}})
text(S, "get_subnet", {}, "< GET IP_SUBNET_NET_AUDIO_PRIMARY >", device_reply="< REP IP_SUBNET_NET_AUDIO_PRIMARY {255.255.255.0  } >", expect_result={'ok': {'kind': 'value', 'value': '255.255.255.0'}})
text(S, "get_gateway", {}, "< GET IP_GATEWAY_NET_AUDIO_PRIMARY >", device_reply="< REP IP_GATEWAY_NET_AUDIO_PRIMARY {192.168.1.1    } >", expect_result={'ok': {'kind': 'value', 'value': '192.168.1.1'}})
text(S, "get_na_device_name", {}, "< GET NA_DEVICE_NAME >", device_reply="< REP NA_DEVICE_NAME {MXN5-ab12                      } >", expect_result={'ok': {'kind': 'value', 'value': 'MXN5-ab12'}})
text(S, "get_mac_address", {}, "< GET CONTROL_MAC_ADDR >", device_reply="< REP CONTROL_MAC_ADDR 00:0E:DD:FF:F1:63 >", expect_result={'ok': {'kind': 'value', 'value': '00:0E:DD:FF:F1:63'}})
text(S, "get_encryption", {}, "< GET ENCRYPTION >", device_reply="< REP ENCRYPTION ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_preset", {}, "< GET PRESET >", device_reply="< REP PRESET 03 >", expect_result={'ok': {'kind': 'value', 'value': '03'}})
text(S, "recall_preset", {'preset': 3}, "< SET PRESET 03 >", device_reply="< REP PRESET 03 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "recall_preset", {'preset': 10}, "< SET PRESET 10 >", device_reply="< REP ERR >", expect_result={'error': {'error': 'device_error'}})
text(S, "get_preset_name", {'preset': 2}, "< GET PRESET_NAME 02 >", device_reply="< REP PRESET_NAME 02 Lecture >", expect_result={'ok': {'kind': 'value', 'value': 'Lecture'}})
text(S, "flash", {'enabled': True}, "< SET FLASH ON >", device_reply="< REP FLASH ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "reboot", {}, "< SET REBOOT >", expect_result={'ok': {'kind': 'unverified'}})
text(S, "restore_defaults", {}, "< SET DEFAULT_SETTINGS >", device_reply="< REP DEFAULT_SETTINGS 00 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_all", {'channel': 0}, "< GET 00 ALL >", expect_result={'ok': {'kind': 'unverified'}})
text(S, "get_parameter", {'channel': 1, 'parameter': 'AUDIO_MUTE'}, "< GET 01 AUDIO_MUTE >", device_reply="< REP 01 AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'value', 'value': 'OFF'}})
text(S, "set_parameter", {'channel': 1, 'parameter': 'AUDIO_MUTE', 'value': 'ON'}, "< SET 01 AUDIO_MUTE ON >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_device_parameter", {'parameter': 'ENCRYPTION'}, "< GET ENCRYPTION >", device_reply="< REP ENCRYPTION OFF >", expect_result={'ok': {'kind': 'value', 'value': 'OFF'}})
text(S, "set_device_parameter", {'parameter': 'LED_BRIGHTNESS', 'value': '2'}, "< SET LED_BRIGHTNESS 2 >", device_reply="< REP LED_BRIGHTNESS 2 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_name", {'channel': 1}, "< GET 01 CHAN_NAME >", device_reply="< REP 01 CHAN_NAME {Podium                         } >", expect_result={'ok': {'kind': 'value', 'value': 'Podium'}})
text(S, "get_mute", {'channel': 1}, "< GET 01 AUDIO_MUTE >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_mute", {'channel': 1, 'muted': True}, "< SET 01 AUDIO_MUTE ON >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_mute", {'channel': 1}, "< SET 01 AUDIO_MUTE TOGGLE >", device_reply="< REP 01 AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_gain", {'channel': 1}, "< GET 01 AUDIO_GAIN_HI_RES >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'value', 'value': '1040'}})
text(S, "set_gain", {'channel': 1, 'gain_tenth_db': -60}, "< SET 01 AUDIO_GAIN_HI_RES 1040 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "increase_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN_HI_RES inc 10 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "decrease_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN_HI_RES dec 10 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_device_mute", {}, "< GET DEVICE_AUDIO_MUTE >", device_reply="< REP DEVICE_AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_device_mute", {'muted': True}, "< SET DEVICE_AUDIO_MUTE ON >", device_reply="< REP DEVICE_AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_device_mute", {}, "< SET DEVICE_AUDIO_MUTE TOGGLE >", device_reply="< REP DEVICE_AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_clip_indicator", {'channel': 1}, "< GET 01 AUDIO_OUT_CLIP_INDICATOR >", device_reply="< REP 01 AUDIO_OUT_CLIP_INDICATOR ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_limiter_engaged", {'channel': 1}, "< GET 01 LIMITER_ENGAGED >", device_reply="< REP 01 LIMITER_ENGAGED ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_meter_rate", {}, "< GET METER_RATE >", device_reply="< REP METER_RATE 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate", {'rate_ms': 1000}, "< SET METER_RATE 01000 >", device_reply="< REP METER_RATE 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_delay", {'channel': 3}, "< GET 03 DELAY >", device_reply="< REP 03 DELAY 0010 >", expect_result={'ok': {'kind': 'value', 'value': '0010'}})
text(S, "set_delay", {'channel': 3, 'value': 160}, "< SET 03 DELAY 0160 >", device_reply="< REP 03 DELAY 0160 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_bypass_dsp", {}, "< GET BYPASS_DSP >", device_reply="< REP BYPASS_DSP ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_bypass_dsp", {'enabled': True}, "< SET BYPASS_DSP ON >", device_reply="< REP BYPASS_DSP ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_bypass_dsp", {}, "< SET BYPASS_DSP TOGGLE >", device_reply="< REP BYPASS_DSP OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_signal_generator_type", {'channel': 3}, "< GET 03 SIG_GEN_TYPE >", device_reply="< REP 03 SIG_GEN_TYPE PINK >", expect_result={'ok': {'kind': 'value', 'value': 'PINK'}})
text(S, "set_signal_generator_type", {'channel': 3, 'value': 'SWEEP'}, "< SET 03 SIG_GEN_TYPE SWEEP >", device_reply="< REP 03 SIG_GEN_TYPE SWEEP >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_signal_generator_frequency", {'channel': 3}, "< GET 03 SIG_GEN_FREQ >", device_reply="< REP 03 SIG_GEN_FREQ 1000 >", expect_result={'ok': {'kind': 'value', 'value': '1000'}})
text(S, "set_signal_generator_frequency", {'channel': 3, 'frequency_hz': 1000}, "< SET 03 SIG_GEN_FREQ 1000 >", device_reply="< REP 03 SIG_GEN_FREQ 1000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_signal_generator_gain", {'channel': 3}, "< GET 03 SIG_GEN_GAIN >", device_reply="< REP 03 SIG_GEN_GAIN 0900 >", expect_result={'ok': {'kind': 'value', 'value': '0900'}})
text(S, "set_signal_generator_gain", {'channel': 3, 'gain_tenth_db': -200}, "< SET 03 SIG_GEN_GAIN 0900 >", device_reply="< REP 03 SIG_GEN_GAIN 0900 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "set_signal_generator", {'channel': 3, 'state': 'STOP'}, "< SET 03 SIG_GEN STOP >", device_reply="< REP 03 SIG_GEN STOP >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_peq_filter", {'block': 1, 'filter': 2}, "< GET 01 PEQ 02 >", device_reply="< REP 01 PEQ 02 ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_peq_filter", {'block': 1, 'filter': 2, 'state': 'OFF'}, "< SET 01 PEQ 02 OFF >", device_reply="< REP 01 PEQ 02 OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_mute", {'channel': 2}, "< GET 02 AUDIO_MUTE >", device_reply="< REP ERR >", expect_result={'error': {'error': 'device_error'}})
telemetry(S, "mute-gain-name", inbound="< REP 01 AUDIO_MUTE ON >< REP 01 AUDIO_GAIN_HI_RES 1040 >< REP 01 CHAN_NAME {Podium     } >< REP PRESET 03 >", expect_state={'channels': {'1': {'mute': True, 'gain': -6.0, 'name': 'Podium'}}, 'device': {'preset': 3}})
