S = "shure-mxa"
# Generated with the spec from Shure's command-string documents (see the spec's sources).
text(S, "get_model", {}, "< GET MODEL >", device_reply="< REP MODEL {P300                            } >", expect_result={'ok': {'kind': 'value', 'value': 'P300'}})
text(S, "get_serial_number", {}, "< GET SERIAL_NUM >", device_reply="< REP SERIAL_NUM {3TA1234567                      } >", expect_result={'ok': {'kind': 'value', 'value': '3TA1234567'}})
text(S, "get_firmware", {}, "< GET FW_VER >", device_reply="< REP FW_VER {4.4.10            } >", expect_result={'ok': {'kind': 'value', 'value': '4.4.10'}})
text(S, "get_device_id", {}, "< GET DEVICE_ID >", device_reply="< REP DEVICE_ID {Room 101                       } >", expect_result={'ok': {'kind': 'value', 'value': 'Room 101'}})
text(S, "get_ip_address", {}, "< GET IP_ADDR_NET_AUDIO_PRIMARY >", device_reply="< REP IP_ADDR_NET_AUDIO_PRIMARY {192.168.1.20   } >", expect_result={'ok': {'kind': 'value', 'value': '192.168.1.20'}})
text(S, "get_subnet", {}, "< GET IP_SUBNET_NET_AUDIO_PRIMARY >", device_reply="< REP IP_SUBNET_NET_AUDIO_PRIMARY {255.255.255.0  } >", expect_result={'ok': {'kind': 'value', 'value': '255.255.255.0'}})
text(S, "get_gateway", {}, "< GET IP_GATEWAY_NET_AUDIO_PRIMARY >", device_reply="< REP IP_GATEWAY_NET_AUDIO_PRIMARY {192.168.1.1    } >", expect_result={'ok': {'kind': 'value', 'value': '192.168.1.1'}})
text(S, "get_na_device_name", {}, "< GET NA_DEVICE_NAME >", device_reply="< REP NA_DEVICE_NAME {MXA920-ab12                    } >", expect_result={'ok': {'kind': 'value', 'value': 'MXA920-ab12'}})
text(S, "get_mac_address", {}, "< GET CONTROL_MAC_ADDR >", device_reply="< REP CONTROL_MAC_ADDR 00:0E:DD:FF:F1:63 >", expect_result={'ok': {'kind': 'value', 'value': '00:0E:DD:FF:F1:63'}})
text(S, "get_encryption", {}, "< GET ENCRYPTION >", device_reply="< REP ENCRYPTION ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_preset", {}, "< GET PRESET >", device_reply="< REP PRESET 03 >", expect_result={'ok': {'kind': 'value', 'value': '03'}})
text(S, "recall_preset", {'preset': 3}, "< SET PRESET 03 >", device_reply="< REP PRESET 03 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "recall_preset", {'preset': 10}, "< SET PRESET 10 >", device_reply="< REP ERR >", expect_result={'error': {'error': 'device_error'}})
text(S, "get_preset_name", {'preset': 2}, "< GET PRESET_NAME 02 >", device_reply="< REP PRESET_NAME 02 Lecture >", expect_result={'ok': {'kind': 'value', 'value': 'Lecture'}})
text(S, "flash", {'enabled': True}, "< SET FLASH ON >", device_reply="< REP FLASH ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "reboot", {}, "< SET REBOOT >", expect_result={'ok': {'kind': 'unverified'}})
text(S, "restore_defaults", {}, "< SET DEFAULT_SETTINGS >", device_reply="< REP DEFAULT_SETTINGS 00 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_all", {'channel': 0}, "< GET 00 ALL >", expect_result={'ok': {'kind': 'unverified'}})
text(S, "get_parameter", {'channel': 1, 'parameter': 'AUDIO_MUTE'}, "< GET 01 AUDIO_MUTE >", device_reply="< REP 01 AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'value', 'value': 'OFF'}})
text(S, "set_parameter", {'channel': 1, 'parameter': 'AUDIO_MUTE', 'value': 'ON'}, "< SET 01 AUDIO_MUTE ON >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_device_parameter", {'parameter': 'ENCRYPTION'}, "< GET ENCRYPTION >", device_reply="< REP ENCRYPTION OFF >", expect_result={'ok': {'kind': 'value', 'value': 'OFF'}})
text(S, "set_device_parameter", {'parameter': 'LED_BRIGHTNESS', 'value': '2'}, "< SET LED_BRIGHTNESS 2 >", device_reply="< REP LED_BRIGHTNESS 2 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_name", {'channel': 1}, "< GET 01 CHAN_NAME >", device_reply="< REP 01 CHAN_NAME {Podium                         } >", expect_result={'ok': {'kind': 'value', 'value': 'Podium'}})
text(S, "get_mute", {'channel': 1}, "< GET 01 AUDIO_MUTE >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_mute", {'channel': 1, 'muted': True}, "< SET 01 AUDIO_MUTE ON >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_mute", {'channel': 1}, "< SET 01 AUDIO_MUTE TOGGLE >", device_reply="< REP 01 AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_gain", {'channel': 1}, "< GET 01 AUDIO_GAIN_HI_RES >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'value', 'value': '1040'}})
text(S, "set_gain", {'channel': 1, 'gain_tenth_db': -60}, "< SET 01 AUDIO_GAIN_HI_RES 1040 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "increase_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN_HI_RES inc 10 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "decrease_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN_HI_RES dec 10 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_postgate_gain", {'channel': 1}, "< GET 01 AUDIO_GAIN_POSTGATE >", device_reply="< REP 01 AUDIO_GAIN_POSTGATE 1100 >", expect_result={'ok': {'kind': 'value', 'value': '1100'}})
text(S, "set_postgate_gain", {'channel': 1, 'gain_tenth_db': 0}, "< SET 01 AUDIO_GAIN_POSTGATE 1100 >", device_reply="< REP 01 AUDIO_GAIN_POSTGATE 1100 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_device_mute", {}, "< GET DEVICE_AUDIO_MUTE >", device_reply="< REP DEVICE_AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_device_mute", {'muted': True}, "< SET DEVICE_AUDIO_MUTE ON >", device_reply="< REP DEVICE_AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_device_mute", {}, "< SET DEVICE_AUDIO_MUTE TOGGLE >", device_reply="< REP DEVICE_AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_postgate_mute", {'channel': 1}, "< GET 01 AUDIO_MUTE_POSTGATE >", device_reply="< REP 01 AUDIO_MUTE_POSTGATE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_postgate_mute", {'channel': 1, 'muted': True}, "< SET 01 AUDIO_MUTE_POSTGATE ON >", device_reply="< REP 01 AUDIO_MUTE_POSTGATE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_postgate_mute", {'channel': 1}, "< SET 01 AUDIO_MUTE_POSTGATE TOGGLE >", device_reply="< REP 01 AUDIO_MUTE_POSTGATE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_coverage_mute", {'channel': 1}, "< GET 01 CA_MUTE >", device_reply="< REP 01 CA_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_coverage_mute", {'channel': 1, 'muted': True}, "< SET 01 CA_MUTE ON >", device_reply="< REP 01 CA_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_coverage_mute", {'channel': 1}, "< SET 01 CA_MUTE TOGGLE >", device_reply="< REP 01 CA_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_coverage_gain", {'channel': 1}, "< GET 01 CA_GAIN >", device_reply="< REP 01 CA_GAIN 1100 >", expect_result={'ok': {'kind': 'value', 'value': '1100'}})
text(S, "set_coverage_gain", {'channel': 1, 'gain_tenth_db': -60}, "< SET 01 CA_GAIN 1040 >", device_reply="< REP 01 CA_GAIN 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_clip_indicator", {'channel': 1}, "< GET 01 AUDIO_OUT_CLIP_INDICATOR >", device_reply="< REP 01 AUDIO_OUT_CLIP_INDICATOR ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_active_mics", {}, "< GET NUM_ACTIVE_MICS >", device_reply="< REP NUM_ACTIVE_MICS 2 >", expect_result={'ok': {'kind': 'value', 'value': '2'}})
text(S, "get_solo", {'channel': 1}, "< GET 01 CHAN_AUTOMIX_SOLO_EN >", device_reply="< REP 01 CHAN_AUTOMIX_SOLO_EN DISABLE >", expect_result={'ok': {'kind': 'value', 'value': 'DISABLE'}})
text(S, "set_solo", {'channel': 1, 'value': 'DISABLE'}, "< SET 01 CHAN_AUTOMIX_SOLO_EN DISABLE >", device_reply="< REP 01 CHAN_AUTOMIX_SOLO_EN DISABLE >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_gate_out", {'channel': 1}, "< GET 01 AUTOMIX_GATE_OUT_EXT_SIG >", device_reply="< REP 01 AUTOMIX_GATE_OUT_EXT_SIG ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_coverage_gate_out", {'channel': 1}, "< GET 01 AUTOMIX_GATE_OUT_CA >", device_reply="< REP 01 AUTOMIX_GATE_OUT_CA ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_speech_gating", {'channel': 9}, "< GET 09 SPEECH_GATING >", device_reply="< REP 09 SPEECH_GATING Low >", expect_result={'ok': {'kind': 'value', 'value': 'Low'}})
text(S, "set_speech_gating", {'channel': 9, 'value': 'OFF'}, "< SET 09 SPEECH_GATING OFF >", device_reply="< REP 09 SPEECH_GATING OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_noise_filter", {'channel': 9}, "< GET 09 NOISE_FILTER >", device_reply="< REP 09 NOISE_FILTER Off >", expect_result={'ok': {'kind': 'value', 'value': 'Off'}})
text(S, "set_noise_filter", {'channel': 9, 'value': 'OFF'}, "< SET 09 NOISE_FILTER OFF >", device_reply="< REP 09 NOISE_FILTER OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate", {}, "< GET METER_RATE >", device_reply="< REP METER_RATE 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate", {'rate_ms': 1000}, "< SET METER_RATE 01000 >", device_reply="< REP METER_RATE 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate_postgate", {}, "< GET METER_RATE_POSTGATE >", device_reply="< REP METER_RATE_POSTGATE 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate_postgate", {'rate_ms': 1000}, "< SET METER_RATE_POSTGATE 01000 >", device_reply="< REP METER_RATE_POSTGATE 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate_mixer_gain", {}, "< GET METER_RATE_MXR_GAIN >", device_reply="< REP METER_RATE_MXR_GAIN 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate_mixer_gain", {'rate_ms': 1000}, "< SET METER_RATE_MXR_GAIN 01000 >", device_reply="< REP METER_RATE_MXR_GAIN 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate_precomp", {}, "< GET METER_RATE_PRECOMP >", device_reply="< REP METER_RATE_PRECOMP 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate_precomp", {'rate_ms': 1000}, "< SET METER_RATE_PRECOMP 01000 >", device_reply="< REP METER_RATE_PRECOMP 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate_aec_reference", {}, "< GET METER_RATE_AECREF >", device_reply="< REP METER_RATE_AECREF 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate_aec_reference", {'rate_ms': 1000}, "< SET METER_RATE_AECREF 01000 >", device_reply="< REP METER_RATE_AECREF 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_meter_rate_coverage", {}, "< GET CA_METER_RATE >", device_reply="< REP CA_METER_RATE 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate_coverage", {'rate_ms': 1000}, "< SET CA_METER_RATE 01000 >", device_reply="< REP CA_METER_RATE 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_mute_led", {}, "< GET DEV_MUTE_STATUS_LED_STATE >", device_reply="< REP DEV_MUTE_STATUS_LED_STATE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_led_brightness", {}, "< GET LED_BRIGHTNESS >", device_reply="< REP LED_BRIGHTNESS 5 >", expect_result={'ok': {'kind': 'value', 'value': '5'}})
text(S, "set_led_brightness", {'value': 5}, "< SET LED_BRIGHTNESS 5 >", device_reply="< REP LED_BRIGHTNESS 5 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_led_color_unmuted", {}, "< GET LED_COLOR_UNMUTED >", device_reply="< REP LED_COLOR_UNMUTED GREEN >", expect_result={'ok': {'kind': 'value', 'value': 'GREEN'}})
text(S, "set_led_color_unmuted", {'value': 'WHITE'}, "< SET LED_COLOR_UNMUTED WHITE >", device_reply="< REP LED_COLOR_UNMUTED WHITE >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_led_color_muted", {}, "< GET LED_COLOR_MUTED >", device_reply="< REP LED_COLOR_MUTED RED >", expect_result={'ok': {'kind': 'value', 'value': 'RED'}})
text(S, "set_led_color_muted", {'value': 'WHITE'}, "< SET LED_COLOR_MUTED WHITE >", device_reply="< REP LED_COLOR_MUTED WHITE >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_led_state_muted", {}, "< GET LED_STATE_MUTED >", device_reply="< REP LED_STATE_MUTED ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_led_state_muted", {'value': 'OFF'}, "< SET LED_STATE_MUTED OFF >", device_reply="< REP LED_STATE_MUTED OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_led_state_unmuted", {}, "< GET LED_STATE_UNMUTED >", device_reply="< REP LED_STATE_UNMUTED ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_led_state_unmuted", {'value': 'OFF'}, "< SET LED_STATE_UNMUTED OFF >", device_reply="< REP LED_STATE_UNMUTED OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_led_in", {}, "< GET DEV_LED_IN_STATE >", device_reply="< REP DEV_LED_IN_STATE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_led_in", {'enabled': True}, "< SET DEV_LED_IN_STATE ON >", device_reply="< REP DEV_LED_IN_STATE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_bypass_eq", {}, "< GET BYPASS_ALL_EQ >", device_reply="< REP BYPASS_ALL_EQ ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_bypass_eq", {'enabled': True}, "< SET BYPASS_ALL_EQ ON >", device_reply="< REP BYPASS_ALL_EQ ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_bypass_eq", {}, "< SET BYPASS_ALL_EQ TOGGLE >", device_reply="< REP BYPASS_ALL_EQ OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_bypass_intellimix", {}, "< GET BYPASS_IMX >", device_reply="< REP BYPASS_IMX ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_bypass_intellimix", {'enabled': True}, "< SET BYPASS_IMX ON >", device_reply="< REP BYPASS_IMX ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_bypass_intellimix", {}, "< SET BYPASS_IMX TOGGLE >", device_reply="< REP BYPASS_IMX OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_eq_contour", {}, "< GET EQ_CONTOUR >", device_reply="< REP EQ_CONTOUR ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_eq_contour", {'enabled': True}, "< SET EQ_CONTOUR ON >", device_reply="< REP EQ_CONTOUR ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_lobe_width", {'channel': 1}, "< GET 01 BEAM_W >", device_reply="< REP 01 BEAM_W MEDIUM >", expect_result={'ok': {'kind': 'value', 'value': 'MEDIUM'}})
text(S, "set_lobe_width", {'channel': 1, 'value': 'WIDE'}, "< SET 01 BEAM_W WIDE >", device_reply="< REP 01 BEAM_W WIDE >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_lobe_x", {'channel': 1}, "< GET 01 BEAM_X >", device_reply="< REP 01 BEAM_X 1067 >", expect_result={'ok': {'kind': 'value', 'value': '1067'}})
text(S, "set_lobe_x", {'channel': 1, 'position_cm': -457}, "< SET 01 BEAM_X 1067 >", device_reply="< REP 01 BEAM_X 1067 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_autofocus_x", {'channel': 1}, "< GET 01 BEAM_X_AF >", device_reply="< REP 01 BEAM_X_AF 1524 >", expect_result={'ok': {'kind': 'value', 'value': '1524'}})
text(S, "get_lobe_y", {'channel': 1}, "< GET 01 BEAM_Y >", device_reply="< REP 01 BEAM_Y 1067 >", expect_result={'ok': {'kind': 'value', 'value': '1067'}})
text(S, "set_lobe_y", {'channel': 1, 'position_cm': -457}, "< SET 01 BEAM_Y 1067 >", device_reply="< REP 01 BEAM_Y 1067 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_autofocus_y", {'channel': 1}, "< GET 01 BEAM_Y_AF >", device_reply="< REP 01 BEAM_Y_AF 1524 >", expect_result={'ok': {'kind': 'value', 'value': '1524'}})
text(S, "get_lobe_z", {'channel': 1}, "< GET 01 BEAM_Z >", device_reply="< REP 01 BEAM_Z 0152 >", expect_result={'ok': {'kind': 'value', 'value': '0152'}})
text(S, "set_lobe_z", {'channel': 1, 'height_cm': 152}, "< SET 01 BEAM_Z 0152 >", device_reply="< REP 01 BEAM_Z 0152 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_autofocus_z", {'channel': 1}, "< GET 01 BEAM_Z_AF >", device_reply="< REP 01 BEAM_Z_AF 0152 >", expect_result={'ok': {'kind': 'value', 'value': '0152'}})
text(S, "get_autofocus", {}, "< GET AUTOFOCUS >", device_reply="< REP AUTOFOCUS ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_autofocus", {'enabled': True}, "< SET AUTOFOCUS ON >", device_reply="< REP AUTOFOCUS ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_array_height", {}, "< GET ARRAY_HEIGHT >", device_reply="< REP ARRAY_HEIGHT 274 >", expect_result={'ok': {'kind': 'value', 'value': '274'}})
text(S, "set_array_height", {'height_cm': 274}, "< SET ARRAY_HEIGHT 274 >", device_reply="< REP ARRAY_HEIGHT 274 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automatic_coverage", {}, "< GET AUTO_COVERAGE >", device_reply="< REP AUTO_COVERAGE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_automatic_coverage", {'enabled': True}, "< SET AUTO_COVERAGE ON >", device_reply="< REP AUTO_COVERAGE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_acoustic_boundary", {}, "< GET VAB >", device_reply="< REP VAB 5 >", expect_result={'ok': {'kind': 'value', 'value': '5'}})
text(S, "set_acoustic_boundary", {'value': 20}, "< SET VAB 20 >", device_reply="< REP VAB 20 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_talker_position_rate", {}, "< GET TALKER_POSITION_RATE >", device_reply="< REP TALKER_POSITION_RATE 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_talker_position_rate", {'rate_ms': 1000}, "< SET TALKER_POSITION_RATE 01000 >", device_reply="< REP TALKER_POSITION_RATE 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_talker_sensitivity", {}, "< GET TALKER_POSITION_SENSITIVITY >", device_reply="< REP TALKER_POSITION_SENSITIVITY 0 >", expect_result={'ok': {'kind': 'value', 'value': '0'}})
text(S, "set_talker_sensitivity", {'value': 11}, "< SET TALKER_POSITION_SENSITIVITY 11 >", device_reply="< REP TALKER_POSITION_SENSITIVITY 11 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_installation", {}, "< GET DEVICE_INSTALLATION >", device_reply="< REP DEVICE_INSTALLATION TABLE >", expect_result={'ok': {'kind': 'value', 'value': 'TABLE'}})
text(S, "set_installation", {'value': 'TABLE'}, "< SET DEVICE_INSTALLATION TABLE >", device_reply="< REP DEVICE_INSTALLATION TABLE >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_lobe_angle", {'channel': 1}, "< GET 01 BEAM_ANGLE >", device_reply="< REP 01 BEAM_ANGLE -30 >", expect_result={'ok': {'kind': 'value', 'value': '-30'}})
text(S, "set_lobe_angle", {'channel': 1, 'angle': -30}, "< SET 01 BEAM_ANGLE -30 >", device_reply="< REP 01 BEAM_ANGLE -30 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_speaker", {}, "< GET SPEAKER >", device_reply="< REP SPEAKER ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_speaker", {'enabled': True}, "< SET SPEAKER ON >", device_reply="< REP SPEAKER ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_delay", {'channel': 10}, "< GET 10 DELAY >", device_reply="< REP 10 DELAY 0010 >", expect_result={'ok': {'kind': 'value', 'value': '0010'}})
text(S, "set_delay", {'channel': 10, 'value': 160}, "< SET 10 DELAY 0160 >", device_reply="< REP 10 DELAY 0160 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_compressor", {'channel': 9}, "< GET 09 COMPRESSOR >", device_reply="< REP 09 COMPRESSOR ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_compressor", {'channel': 9, 'enabled': True}, "< SET 09 COMPRESSOR ON >", device_reply="< REP 09 COMPRESSOR ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_compressor", {'channel': 9}, "< SET 09 COMPRESSOR TOGGLE >", device_reply="< REP 09 COMPRESSOR OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_signal_generator_type", {'channel': 10}, "< GET 10 SIG_GEN_TYPE >", device_reply="< REP 10 SIG_GEN_TYPE PINK >", expect_result={'ok': {'kind': 'value', 'value': 'PINK'}})
text(S, "set_signal_generator_type", {'channel': 10, 'value': 'TONE'}, "< SET 10 SIG_GEN_TYPE TONE >", device_reply="< REP 10 SIG_GEN_TYPE TONE >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_signal_generator_frequency", {'channel': 10}, "< GET 10 SIG_GEN_FREQ >", device_reply="< REP 10 SIG_GEN_FREQ 1000 >", expect_result={'ok': {'kind': 'value', 'value': '1000'}})
text(S, "set_signal_generator_frequency", {'channel': 10, 'frequency_hz': 1000}, "< SET 10 SIG_GEN_FREQ 1000 >", device_reply="< REP 10 SIG_GEN_FREQ 1000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_signal_generator", {'channel': 10}, "< GET 10 SIG_GEN >", device_reply="< REP 10 SIG_GEN STOP >", expect_result={'ok': {'kind': 'value', 'value': 'STOP'}})
text(S, "set_signal_generator", {'channel': 10, 'value': 'TOGGLE'}, "< SET 10 SIG_GEN TOGGLE >", device_reply="< REP 10 SIG_GEN TOGGLE >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_polar_pattern", {'channel': 1}, "< GET 01 POLAR_PATTERN >", device_reply="< REP 01 POLAR_PATTERN CARDIOID >", expect_result={'ok': {'kind': 'value', 'value': 'CARDIOID'}})
text(S, "set_polar_pattern", {'channel': 1, 'value': 'BIDIRECTION'}, "< SET 01 POLAR_PATTERN BIDIRECTION >", device_reply="< REP 01 POLAR_PATTERN BIDIRECTION >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_mute_button", {}, "< GET MUTE_BUTTON_STATUS >", device_reply="< REP MUTE_BUTTON_STATUS ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_peq_filter", {'block': 1, 'filter': 2}, "< GET 01 PEQ 02 >", device_reply="< REP 01 PEQ 02 ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_peq_filter", {'block': 1, 'filter': 2, 'state': 'OFF'}, "< SET 01 PEQ 02 OFF >", device_reply="< REP 01 PEQ 02 OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_mute", {'channel': 2}, "< GET 02 AUDIO_MUTE >", device_reply="< REP ERR >", expect_result={'error': {'error': 'device_error'}})
telemetry(S, "mute-gain-name", inbound="< REP 01 AUDIO_MUTE ON >< REP 01 AUDIO_GAIN_HI_RES 1040 >< REP 01 CHAN_NAME {Podium     } >< REP PRESET 03 >", expect_state={'channels': {'1': {'mute': True, 'gain': -6.0, 'name': 'Podium'}}, 'device': {'preset': 3}})
