S = "shure-ani"
# Generated with the spec from Shure's command-string documents (see the spec's sources).
text(S, "get_model", {}, "< GET MODEL >", device_reply="< REP MODEL {P300                            } >", expect_result={'ok': {'kind': 'value', 'value': 'P300'}})
text(S, "get_serial_number", {}, "< GET SERIAL_NUM >", device_reply="< REP SERIAL_NUM {3TA1234567                      } >", expect_result={'ok': {'kind': 'value', 'value': '3TA1234567'}})
text(S, "get_firmware", {}, "< GET FW_VER >", device_reply="< REP FW_VER {4.4.10            } >", expect_result={'ok': {'kind': 'value', 'value': '4.4.10'}})
text(S, "get_device_id", {}, "< GET DEVICE_ID >", device_reply="< REP DEVICE_ID {Room 101                       } >", expect_result={'ok': {'kind': 'value', 'value': 'Room 101'}})
text(S, "get_ip_address", {}, "< GET IP_ADDR_NET_AUDIO_PRIMARY >", device_reply="< REP IP_ADDR_NET_AUDIO_PRIMARY {192.168.1.20   } >", expect_result={'ok': {'kind': 'value', 'value': '192.168.1.20'}})
text(S, "get_subnet", {}, "< GET IP_SUBNET_NET_AUDIO_PRIMARY >", device_reply="< REP IP_SUBNET_NET_AUDIO_PRIMARY {255.255.255.0  } >", expect_result={'ok': {'kind': 'value', 'value': '255.255.255.0'}})
text(S, "get_gateway", {}, "< GET IP_GATEWAY_NET_AUDIO_PRIMARY >", device_reply="< REP IP_GATEWAY_NET_AUDIO_PRIMARY {192.168.1.1    } >", expect_result={'ok': {'kind': 'value', 'value': '192.168.1.1'}})
text(S, "get_encryption", {}, "< GET ENCRYPTION >", device_reply="< REP ENCRYPTION ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_preset", {}, "< GET PRESET >", device_reply="< REP PRESET 03 >", expect_result={'ok': {'kind': 'value', 'value': '03'}})
text(S, "recall_preset", {'preset': 3}, "< SET PRESET 03 >", device_reply="< REP PRESET 03 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "recall_preset", {'preset': 10}, "< SET PRESET 10 >", device_reply="< REP ERR >", expect_result={'error': {'error': 'device_error'}})
text(S, "get_preset_name", {'preset': 2}, "< GET PRESET2 >", device_reply="< REP PRESET2 {Lecture                  } >", expect_result={'ok': {'kind': 'value', 'value': 'Lecture'}})
text(S, "flash", {'enabled': True}, "< SET FLASH ON >", device_reply="< REP FLASH ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "reboot", {}, "< SET REBOOT >", expect_result={'ok': {'kind': 'unverified'}})
text(S, "restore_defaults", {}, "< SET DEFAULT_SETTINGS >", device_reply="< REP DEFAULT_SETTINGS 00 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_all", {'channel': 0}, "< GET 00 ALL >", expect_result={'ok': {'kind': 'unverified'}})
text(S, "get_parameter", {'channel': 1, 'parameter': 'AUDIO_MUTE'}, "< GET 01 AUDIO_MUTE >", device_reply="< REP 01 AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'value', 'value': 'OFF'}})
text(S, "set_parameter", {'channel': 1, 'parameter': 'AUDIO_MUTE', 'value': 'ON'}, "< SET 01 AUDIO_MUTE ON >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_device_parameter", {'parameter': 'ENCRYPTION'}, "< GET ENCRYPTION >", device_reply="< REP ENCRYPTION OFF >", expect_result={'ok': {'kind': 'value', 'value': 'OFF'}})
text(S, "set_device_parameter", {'parameter': 'LED_BRIGHTNESS', 'value': '2'}, "< SET LED_BRIGHTNESS 2 >", device_reply="< REP LED_BRIGHTNESS 2 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_name", {'channel': 1}, "< GET 01 CHAN_NAME >", device_reply="< REP 01 CHAN_NAME {Podium                         } >", expect_result={'ok': {'kind': 'value', 'value': 'Podium'}})
text(S, "get_mute", {'channel': 1}, "< GET 01 AUDIO_MUTE >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_mute", {'channel': 1, 'muted': True}, "< SET 01 AUDIO_MUTE ON >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_mute", {'channel': 1}, "< SET 01 AUDIO_MUTE TOGGLE >", device_reply="< REP 01 AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_gain", {'channel': 1}, "< GET 01 AUDIO_GAIN_HI_RES >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'value', 'value': '1040'}})
text(S, "set_gain", {'channel': 1, 'gain_tenth_db': -60}, "< SET 01 AUDIO_GAIN_HI_RES 1040 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "increase_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN_HI_RES INC 10 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "decrease_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN_HI_RES DEC 10 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_analog_gain", {'channel': 1}, "< GET 01 AUDIO_GAIN >", device_reply="< REP 01 AUDIO_GAIN 24 >", expect_result={'ok': {'kind': 'value', 'value': '24'}})
text(S, "set_analog_gain", {'channel': 1, 'gain_db': 24}, "< SET 01 AUDIO_GAIN 24 >", device_reply="< REP 01 AUDIO_GAIN 24 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "increase_analog_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN INC 10 >", device_reply="< REP 01 AUDIO_GAIN 24 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "decrease_analog_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN DEC 10 >", device_reply="< REP 01 AUDIO_GAIN 24 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_device_mute", {}, "< GET DEVICE_AUDIO_MUTE >", device_reply="< REP DEVICE_AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_device_mute", {'muted': True}, "< SET DEVICE_AUDIO_MUTE ON >", device_reply="< REP DEVICE_AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_device_mute", {}, "< SET DEVICE_AUDIO_MUTE TOGGLE >", device_reply="< REP DEVICE_AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_output_level", {'channel': 1}, "< GET 01 AUDIO_OUT_LVL_SWITCH >", device_reply="< REP 01 AUDIO_OUT_LVL_SWITCH LINE_LVL >", expect_result={'ok': {'kind': 'value', 'value': 'LINE_LVL'}})
text(S, "set_output_level", {'channel': 1, 'value': 'MIC_LVL'}, "< SET 01 AUDIO_OUT_LVL_SWITCH MIC_LVL >", device_reply="< REP 01 AUDIO_OUT_LVL_SWITCH MIC_LVL >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_phantom", {'channel': 1}, "< GET 01 PHANTOM_PWR_ENABLE >", device_reply="< REP 01 PHANTOM_PWR_ENABLE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_phantom", {'channel': 1, 'enabled': True}, "< SET 01 PHANTOM_PWR_ENABLE ON >", device_reply="< REP 01 PHANTOM_PWR_ENABLE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_logic_out", {'channel': 1}, "< GET 01 HW_GATING_LOGIC >", device_reply="< REP 01 HW_GATING_LOGIC ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_led_in", {'channel': 1, 'enabled': True}, "< SET 01 CHAN_LED_IN_STATE ON >", expect_result={'ok': {'kind': 'unverified'}})
text(S, "get_clip_indicator", {'channel': 1}, "< GET 01 AUDIO_OUT_CLIP_INDICATOR >", device_reply="< REP 01 AUDIO_OUT_CLIP_INDICATOR ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_limiter_engaged", {'channel': 1}, "< GET 01 LIMITER_ENGAGED >", device_reply="< REP 01 LIMITER_ENGAGED ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_sig_clip_led", {'channel': 1}, "< GET 01 LED_COLOR_SIG_CLIP >", device_reply="< REP 01 LED_COLOR_SIG_CLIP GREEN >", expect_result={'ok': {'kind': 'value', 'value': 'GREEN'}})
text(S, "get_led_brightness", {}, "< GET LED_BRIGHTNESS >", device_reply="< REP LED_BRIGHTNESS 2 >", expect_result={'ok': {'kind': 'value', 'value': '2'}})
text(S, "set_led_brightness", {'value': 2}, "< SET LED_BRIGHTNESS 2 >", device_reply="< REP LED_BRIGHTNESS 2 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_summing_mode", {}, "< GET AUDIO_SUMMING_MODE >", device_reply="< REP AUDIO_SUMMING_MODE OFF >", expect_result={'ok': {'kind': 'value', 'value': 'OFF'}})
text(S, "set_summing_mode", {'value': '1+2+3+4'}, "< SET AUDIO_SUMMING_MODE 1+2+3+4 >", device_reply="< REP AUDIO_SUMMING_MODE 1+2+3+4 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_input_meter_mode", {}, "< GET INPUT_METER_MODE >", device_reply="< REP INPUT_METER_MODE PRE_FADER >", expect_result={'ok': {'kind': 'value', 'value': 'PRE_FADER'}})
text(S, "set_input_meter_mode", {'value': 'POST_FADER'}, "< SET INPUT_METER_MODE POST_FADER >", device_reply="< REP INPUT_METER_MODE POST_FADER >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_output_meter_mode", {}, "< GET OUTPUT_METER_MODE >", device_reply="< REP OUTPUT_METER_MODE PRE_FADER >", expect_result={'ok': {'kind': 'value', 'value': 'PRE_FADER'}})
text(S, "set_output_meter_mode", {'value': 'POST_FADER'}, "< SET OUTPUT_METER_MODE POST_FADER >", device_reply="< REP OUTPUT_METER_MODE POST_FADER >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_usb_connected", {}, "< GET USB_CONNECT >", device_reply="< REP USB_CONNECT ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_logic_mute", {}, "< GET LOGIC_MUTE >", device_reply="< REP LOGIC_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_logic_mute", {'muted': True}, "< SET LOGIC_MUTE ON >", device_reply="< REP LOGIC_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_logic_mute", {}, "< SET LOGIC_MUTE TOGGLE >", device_reply="< REP LOGIC_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_last_error", {}, "< GET LAST_ERROR_EVENT >", device_reply="< REP LAST_ERROR_EVENT {none} >", expect_result={'ok': {'kind': 'value', 'value': 'none'}})
text(S, "get_meter_rate", {}, "< GET METER_RATE >", device_reply="< REP METER_RATE 01000 >", expect_result={'ok': {'kind': 'value', 'value': '01000'}})
text(S, "set_meter_rate", {'rate_ms': 1000}, "< SET METER_RATE 01000 >", device_reply="< REP METER_RATE 01000 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_matrix_route", {'input': 1, 'output': 15}, "< GET 01 MATRIX_MXR_ROUTE 15 >", device_reply="< REP 01 MATRIX_MXR_ROUTE 15 ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_matrix_route", {'input': 1, 'output': 15, 'enabled': False}, "< SET 01 MATRIX_MXR_ROUTE 15 OFF >", device_reply="< REP 01 MATRIX_MXR_ROUTE 15 OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "set_matrix_gain", {'input': 21, 'output': 17, 'gain_tenth_db': -35}, "< SET 21 MATRIX_MXR_GAIN 17 1065 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1065 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_matrix_gain", {'input': 21, 'output': 17}, "< GET 21 MATRIX_MXR_GAIN 17 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1100 >", expect_result={'ok': {'kind': 'value', 'value': 0.0}})
text(S, "increase_matrix_gain", {'input': 21, 'output': 17, 'step': 25}, "< SET 21 MATRIX_MXR_GAIN 17 INC 25 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1125 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "decrease_matrix_gain", {'input': 21, 'output': 17, 'step': 25}, "< SET 21 MATRIX_MXR_GAIN 17 DEC 25 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1125 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_peq_filter", {'block': 1, 'filter': 2}, "< GET 01 PEQ 02 >", device_reply="< REP 01 PEQ 02 ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_peq_filter", {'block': 1, 'filter': 2, 'state': 'OFF'}, "< SET 01 PEQ 02 OFF >", device_reply="< REP 01 PEQ 02 OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_mute", {'channel': 2}, "< GET 02 AUDIO_MUTE >", device_reply="< REP ERR >", expect_result={'error': {'error': 'device_error'}})
telemetry(S, "mute-gain-name", inbound="< REP 01 AUDIO_MUTE ON >< REP 01 AUDIO_GAIN_HI_RES 1040 >< REP 01 CHAN_NAME {Podium     } >< REP PRESET 03 >", expect_state={'channels': {'1': {'mute': True, 'gain': -6.0, 'name': 'Podium'}}, 'device': {'preset': 3}})
