S = "shure-imx-room"
# Generated with the spec from Shure's command-string documents (see the spec's sources).
text(S, "get_model", {}, "< GET MODEL >", device_reply="< REP MODEL {IntelliMix Room                 } >", expect_result={'ok': {'kind': 'value', 'value': 'IntelliMix Room'}})
text(S, "get_firmware", {}, "< GET FW_VER >", device_reply="< REP FW_VER {7.5.0             } >", expect_result={'ok': {'kind': 'value', 'value': '7.5.0'}})
text(S, "get_device_id", {}, "< GET DEVICE_ID >", device_reply="< REP DEVICE_ID {Room 101                       } >", expect_result={'ok': {'kind': 'value', 'value': 'Room 101'}})
text(S, "get_na_device_name", {}, "< GET NA_DEVICE_NAME >", device_reply="< REP NA_DEVICE_NAME {IMXR-ab12                      } >", expect_result={'ok': {'kind': 'value', 'value': 'IMXR-ab12'}})
text(S, "get_preset", {}, "< GET PRESET >", device_reply="< REP PRESET 03 >", expect_result={'ok': {'kind': 'value', 'value': '03'}})
text(S, "recall_preset", {'preset': 3}, "< SET PRESET 03 >", device_reply="< REP PRESET 03 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_all", {'channel': 0}, "< GET 00 ALL >", expect_result={'ok': {'kind': 'unverified'}})
text(S, "get_device_mute", {}, "< GET DEVICE_AUDIO_MUTE >", device_reply="< REP DEVICE_AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_device_mute", {'muted': True}, "< SET DEVICE_AUDIO_MUTE ON >", device_reply="< REP DEVICE_AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_device_mute", {}, "< SET DEVICE_AUDIO_MUTE TOGGLE >", device_reply="< REP DEVICE_AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_mute", {'channel': 1}, "< GET 01 AUDIO_MUTE >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_mute", {'channel': 1, 'muted': True}, "< SET 01 AUDIO_MUTE ON >", device_reply="< REP 01 AUDIO_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_mute", {'channel': 1}, "< SET 01 AUDIO_MUTE TOGGLE >", device_reply="< REP 01 AUDIO_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_gain", {'channel': 1}, "< GET 01 AUDIO_GAIN_HI_RES >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'value', 'value': '1040'}})
text(S, "set_gain", {'channel': 1, 'gain_tenth_db': -60}, "< SET 01 AUDIO_GAIN_HI_RES 1040 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "increase_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN_HI_RES inc 10 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "decrease_gain", {'channel': 1, 'step': 10}, "< SET 01 AUDIO_GAIN_HI_RES dec 10 >", device_reply="< REP 01 AUDIO_GAIN_HI_RES 1040 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_postgate_gain", {'channel': 1}, "< GET 01 AUDIO_GAIN_POSTGATE >", device_reply="< REP 01 AUDIO_GAIN_POSTGATE 1100 >", expect_result={'ok': {'kind': 'value', 'value': '1100'}})
text(S, "set_postgate_gain", {'channel': 1, 'gain_tenth_db': 0}, "< SET 01 AUDIO_GAIN_POSTGATE 1100 >", device_reply="< REP 01 AUDIO_GAIN_POSTGATE 1100 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_mute", {'channel': 37}, "< GET 37 AUTOMXR_MUTE >", device_reply="< REP 37 AUTOMXR_MUTE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_automixer_mute", {'channel': 37, 'muted': True}, "< SET 37 AUTOMXR_MUTE ON >", device_reply="< REP 37 AUTOMXR_MUTE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "toggle_automixer_mute", {'channel': 37}, "< SET 37 AUTOMXR_MUTE TOGGLE >", device_reply="< REP 37 AUTOMXR_MUTE OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_automixer_gate", {'channel': 1}, "< GET 01 AUTOMXR_GATE >", device_reply="< REP 01 AUTOMXR_GATE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "get_channels_configured", {}, "< GET CHAN_CONFIG >", device_reply="< REP CHAN_CONFIG TRUE >", expect_result={'ok': {'kind': 'value', 'value': 'TRUE'}})
text(S, "get_licensed_channels", {}, "< GET CHAN_COUNT >", device_reply="< REP CHAN_COUNT 16 >", expect_result={'ok': {'kind': 'value', 'value': '16'}})
text(S, "get_licence_expiry", {}, "< GET LIC_EXP_DATE >", device_reply="< REP LIC_EXP_DATE 2026-12-31 >", expect_result={'ok': {'kind': 'value', 'value': '2026-12-31'}})
text(S, "get_licence_type", {}, "< GET LIC_TYPE >", device_reply="< REP LIC_TYPE PAID >", expect_result={'ok': {'kind': 'value', 'value': 'PAID'}})
text(S, "get_licence_valid", {}, "< GET LIC_VALID >", device_reply="< REP LIC_VALID TRUE >", expect_result={'ok': {'kind': 'value', 'value': 'TRUE'}})
text(S, "get_denoiser", {'channel': 37}, "< GET 37 DENOISER_ENABLE >", device_reply="< REP 37 DENOISER_ENABLE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_denoiser", {'channel': 37, 'enabled': True}, "< SET 37 DENOISER_ENABLE ON >", device_reply="< REP 37 DENOISER_ENABLE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_denoiser_level", {'channel': 37}, "< GET 37 DENOISER_LEVEL >", device_reply="< REP 37 DENOISER_LEVEL LOW >", expect_result={'ok': {'kind': 'value', 'value': 'LOW'}})
text(S, "set_denoiser_level", {'channel': 37, 'value': 'HIGH'}, "< SET 37 DENOISER_LEVEL HIGH >", device_reply="< REP 37 DENOISER_LEVEL HIGH >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_call_status_enabled", {}, "< GET ONHOOK_ENABLE >", device_reply="< REP ONHOOK_ENABLE ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_call_status_enabled", {'enabled': True}, "< SET ONHOOK_ENABLE ON >", device_reply="< REP ONHOOK_ENABLE ON >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_call_state", {}, "< GET ONHOOK_STATE >", device_reply="< REP ONHOOK_STATE ONHOOK >", expect_result={'ok': {'kind': 'value', 'value': 'ONHOOK'}})
text(S, "get_matrix_route", {'input': 1, 'output': 15}, "< GET 01 MATRIX_MXR_ROUTE 15 >", device_reply="< REP 01 MATRIX_MXR_ROUTE 15 ON >", expect_result={'ok': {'kind': 'value', 'value': 'ON'}})
text(S, "set_matrix_route", {'input': 1, 'output': 15, 'enabled': False}, "< SET 01 MATRIX_MXR_ROUTE 15 OFF >", device_reply="< REP 01 MATRIX_MXR_ROUTE 15 OFF >", expect_result={'ok': {'kind': 'ack'}})
text(S, "set_matrix_gain", {'input': 21, 'output': 17, 'gain_tenth_db': -35}, "< SET 21 MATRIX_MXR_GAIN 17 1065 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1065 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_matrix_gain", {'input': 21, 'output': 17}, "< GET 21 MATRIX_MXR_GAIN 17 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1100 >", expect_result={'ok': {'kind': 'value', 'value': 0.0}})
text(S, "increase_matrix_gain", {'input': 21, 'output': 17, 'step': 25}, "< SET 21 MATRIX_MXR_GAIN 17 inc 25 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1125 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "decrease_matrix_gain", {'input': 21, 'output': 17, 'step': 25}, "< SET 21 MATRIX_MXR_GAIN 17 dec 25 >", device_reply="< REP 21 MATRIX_MXR_GAIN 17 1125 >", expect_result={'ok': {'kind': 'ack'}})
text(S, "get_mute", {'channel': 2}, "< GET 02 AUDIO_MUTE >", device_reply="< REP ERR >", expect_result={'error': {'error': 'device_error'}})
telemetry(S, "mute-gain-name", inbound="< REP 01 AUDIO_MUTE ON >< REP 01 AUDIO_GAIN_HI_RES 1040 >< REP PRESET 03 >", expect_state={'channels': {'1': {'mute': True, 'gain': -6.0}}, 'device': {'preset': 3}})
