# Turtle AV 4x4 / 8x8 4K60 video wall, matrix and multiviewer: lower-case
# commands ended by "!" (the documents' delimiter), sent as lines with CR LF
# (4x4 manual §13, 8x8 manual §10). Wire forms follow the documents'
# examples: "s output 1 in source 2!", "r output 1 in source!", "s recall
# preset 1!", "recall mx preset 1!", "s cec in 1 on!", "s reboot!".
TM = "turtleav-matrix"
M8 = {"model": "mx88vw"}


def tm(command, input, line, **extra):
    text(TM, command, input, line + "\r\n", **extra)


tm("set_power", {"powered": True}, "s power 1!", device_reply="power on\r\n", expect_result={"ok": {"kind": "ack"}})
tm("route", {"output": 1, "input": 2}, "s output 1 in source 2!",
   device_reply="output1->input2\r\n", expect_result={"ok": {"kind": "ack"}})
tm("route_8x8", {"output": 8, "input": 5}, "s output 8 in source 5!",
   device_reply="E01\r\n", expect_result={"error": {"error": "device_error"}}, **M8)
tm("get_route", {"output": 1}, "r output 1 in source!",
   device_reply="output1->input3\r\n", expect_result={"ok": {"kind": "value", "value": "3"}})
tm("recall_preset", {"preset": 1}, "s recall preset 1!")
tm("save_preset", {"preset": 8}, "s save preset 8!")
tm("recall_matrix_preset", {"preset": 2}, "recall mx preset 2!", **M8)
tm("save_matrix_preset", {"preset": 2}, "save mx preset 2!", **M8)
tm("recall_wall_preset", {"preset": 3}, "recall vw preset 3!", **M8)
tm("set_display_mode", {"mode": 2}, "s display mode 2!")
tm("set_display_mode_8x8", {"mode": 1}, "s display mode 1!", **M8)
tm("set_output_resolution", {"output": 1, "code": 3}, "s output 1 res 3!")
tm("set_output_resolution_8x8", {"output": 0, "code": 24}, "s output 0 res 24!", **M8)
tm("set_output_hdcp", {"output": 1, "mode": 3}, "s output 1 hdcp 3!")
tm("set_output_hdcp_8x8", {"output": 1, "mode": 5}, "s output 1 hdcp 5!", **M8)
tm("set_input_edid", {"input": 1, "code": 1}, "s input 1 edid 1!")
tm("set_input_edid_8x8", {"input": 8, "code": 22}, "s input 8 edid 22!", **M8)
tm("set_multiview_layout", {"layout": 5}, "s multiview 5!")
tm("set_window_source", {"window": 1, "input": 4}, "s window 1 in 4!")
tm("set_wall_layout", {"mode": 1}, "s tw mode 1!")
tm("set_wall_group_input", {"group": 1, "input": 2}, "s tw group 1 input 2!")
tm("set_wall_group_source_8x8", {"group": 1, "input": 6}, "s vw group 1 source 6!", **M8)
tm("route_ext_audio", {"output": 1, "input": 1}, "s output 1 exa in source 1!")
tm("cec_input", {"input": 1, "action": "on"}, "s cec in 1 on!")
tm("cec_output", {"output": 2, "action": "vol+"}, "s cec hdmi out 2 vol+!")
tm("set_panel_lock", {"locked": True}, "s lock 1!")
tm("reboot", {}, "s reboot!")

telemetry(TM, "route", inbound="output1->input1\r\n", expect_state={"outputs": {"1": {"input": 1}}})
telemetry(TM, "power", inbound="power on\r\n", expect_state={"power": True})

# Full control: the remaining commands of both manuals, and every read.
tm("clear_preset", {"preset": 1}, "s clear preset 1!", device_reply="clear preset 1\r\n",
   expect_result={"ok": {"kind": "ack"}})
tm("get_preset", {"preset": 1}, "r preset 1!", device_reply="video/audio crosspoint\r\n",
   expect_result={"ok": {"kind": "value", "value": "video/audio crosspoint"}})
tm("clear_matrix_preset", {"preset": 1}, "clear mx preset 1!", **M8)
tm("get_matrix_preset", {"preset": 1}, "r mx preset 1!", **M8)
tm("save_wall_preset", {"preset": 1}, "save vw preset 1!", **M8)
tm("clear_wall_preset", {"preset": 1}, "clear vw preset 1!", **M8)
tm("get_wall_preset", {"preset": 1}, "r vw preset 1!", **M8)
tm("set_output_csc", {"output": 1, "csc": 1}, "s output 1 csc 1!")
tm("set_output_hmirror", {"output": 1, "enabled": True}, "s output 1 hmirror 1!")
tm("set_output_vmirror", {"output": 1, "enabled": False}, "s output 1 vmirror 0!")
tm("set_output_mirror_8x8", {"output": 1, "mode": 3}, "s output 1 mirror 3!", **M8)
tm("set_output_stream", {"output": 1, "enabled": True}, "s output 1 stream 1!")
tm("set_output_background", {"mode": 1}, "s output bg 1!")
tm("set_input_audio_source", {"input": 1, "source": 1}, "s input 1 as 1!")
tm("set_pip_position", {"position": 3}, "s pip position3!")
tm("set_pip_size", {"size": 3}, "s pip size 3!")
tm("set_dual_mode", {"mode": 1}, "s dual 1 mode!")
tm("set_triple_mode", {"mode": 1}, "s triple 1 mode!")
tm("set_quad_mode", {"mode": 1}, "s quad 1 mode!")
tm("set_user_mode", {"mode": 1}, "s user 1 mode!")
tm("set_window_aspect", {"aspect": 1}, "s aspect 1!")
tm("set_multiview_audio", {"source": 0}, "s mv output audio 0!")
tm("set_multiview_resolution", {"code": 3}, "s mv res 3!")
tm("set_wall_h_bezel", {"bezel": "0"}, "s tw h bezel 0!")
tm("set_wall_v_bezel", {"bezel": "+"}, "s tw v bezel +!")
tm("set_wall_resolution", {"code": 3}, "s tw res 3!")
tm("create_wall_screen", {"rows": 2, "cols": 4}, "create vw screen row 2 col 4!", **M8)
tm("set_screen_output", {"screen": 1, "output": 1}, "s screen 1 output 1!", **M8)
tm("set_wall_group_size", {"group": 1, "rows": 1, "cols": 2}, "s vw group 1 row 1 col 2!", **M8)
tm("set_wall_group_screens", {"group": 2, "screens": "2367"}, "s vw group 2 screen 2367!", **M8)
tm("set_wall_group_h_bezel", {"group": 1, "bezel": 0}, "s vw group 1 hbezel 0!", **M8)
tm("set_wall_group_v_bezel", {"group": 1, "bezel": 0}, "s vw group 1 vbezel 0!", **M8)
tm("set_wall_group_resolution", {"group": 1, "code": 6}, "s vw group 1 out res 6!", **M8)
tm("delete_wall_group", {"group": 1}, "delete vw group 1!", **M8)
tm("set_output_exa", {"output": 1, "enabled": True}, "s output 1 exa 1!")
tm("set_exa_mode", {"mode": 0}, "s output exa mode 0!")
tm("set_beep", {"enabled": True}, "s beep 1!")
tm("set_lcd_time", {"mode": 3}, "s lcd on time 3!")
tm("set_logo", {"text": "Matrix Switch"}, "s logo1 Matrix Switch!")
tm("set_baud_rate", {"rate": 1}, "s baud rate 1!", **M8)
tm("set_fan", {"fans": 2, "enabled": False}, "s fan 2 0!", **M8)
tm("factory_reset", {}, "s reset!")
tm("set_ip_mode", {"mode": 0}, "s ip mode 0!")
tm("set_ip_address", {"address": "192.168.0.100"}, "s ip addr 192.168.0.100!")
tm("set_subnet", {"mask": "255.255.255.0"}, "s subnet 255.255.255.0!")
tm("set_gateway", {"gateway": "192.168.0.1"}, "s gateway 192.168.0.1!")
tm("set_tcp_port", {"port": 8000}, "s tcp/ipport 8000!")
tm("set_telnet_port", {"port": 23}, "s telnet port 23!")
tm("net_reboot", {}, "s net reboot!")


def tmt(name, inbound, state, **extra):
    telemetry(TM, name, inbound=inbound + "\r\n", expect_state=state, **extra)


tmt("route-spaced", "output 2->input 5", {"outputs": {"2": {"input": 5}}}, **M8)
tmt("beep", "beep off", {"beep": False})
tmt("lock", "panel button lock on", {"panel_locked": True})
tmt("lcd", "lcd on 30 seconds", {"lcd": "on 30 seconds"})
tmt("logo", "logo1:Matrix Switch", {"logo": "Matrix Switch"})
tmt("serial", "serial number:12345634534", {"serial": "12345634534"}, **M8)
tmt("firmware-mcu", "mcu fw version :1.00.05", {"firmware": {"mcu": "1.00.05"}}, **M8)
tmt("firmware-web", "web gui version :2.00.07", {"firmware": {"web": "2.00.07"}}, **M8)
tmt("firmware-cpld", "cpld version :1.00.03", {"firmware": {"cpld": "1.00.03"}}, **M8)
tmt("display-mode", "display mode: matrix", {"display_mode": "matrix"})
tmt("resolution", "output 1 resolution: 3840x2160p60", {"outputs": {"1": {"resolution": "3840x2160p60"}}})
tmt("csc", "output 1 csc: rgb444", {"outputs": {"1": {"csc": "rgb444"}}})
tmt("hdcp", "output 1 hdcp: hdcp 1.4", {"outputs": {"1": {"hdcp": "hdcp 1.4"}}})
tmt("mirror-4x4", "output 1 h mirror on, v mirror off", {"outputs": {"1": {"h_mirror": True, "v_mirror": False}}})
tmt("vmirror-4x4", "output1 v mirror on", {"outputs": {"1": {"v_mirror": True}}})
tmt("mirror-8x8", "output 1 h+v mirror on", {"outputs": {"1": {"mirror": "h+v mirror on"}}}, **M8)
tmt("stream", "output 1 stream: enable", {"outputs": {"1": {"stream": True}}})
tmt("background", "output background: black screen", {"background": "black screen"})
tmt("edid", "input 1 edid: 4k60, 2.0ch", {"inputs": {"1": {"edid": "4k60, 2.0ch"}}})
tmt("input-audio", "input 3 select embed analog audio", {"inputs": {"3": {"audio_source": "analog"}}})
tmt("exa", "output 1 ext-audio: enable", {"outputs": {"1": {"exa": True}}})
tmt("exa-input", "output 1 ext-audio ->input 2", {"outputs": {"1": {"exa_input": 2}}})
tmt("exa-mode", "output ext-audio moe: bind to input", {"exa_mode": "bind to input"})
tmt("preset", "recall from preset 1", {"preset": {"recalled": 1}})
tmt("wall-layout", "tv wall mode: 2x2", {"wall": {"layout": "2x2"}})
tmt("wall-h-bezel", "tv wall horizontal bezel: 0", {"wall": {"h_bezel": 0}})
tmt("wall-v-bezel", "tv wall vertical bezel: 2", {"wall": {"v_bezel": 2}})
tmt("wall-group", "tv wall group 1 input: hdmi input 1", {"wall": {"groups": {"1": {"input": 1}}}})
tmt("wall-resolution", "tv wall resolution: 3840x2160p60", {"wall": {"resolution": "3840x2160p60"}})
tmt("multiview", "single screen", {"multiview": {"layout": "single"}})
tmt("window", "window 1 select hdmi 1", {"multiview": {"windows": {"1": {"input": 1}}}})
tmt("pip-position", "pip on upper right", {"multiview": {"pip_position": "upper right"}})
tmt("pip-size", "pip size: large", {"multiview": {"pip_size": "large"}})
tmt("triple-mode", "triple 2 mode", {"multiview": {"triple_mode": 2}})
tmt("aspect", "aspect: full screen", {"multiview": {"aspect": "full screen"}})
tmt("mv-audio", "output audio: follow window 1 selected source",
    {"multiview": {"audio": "follow window 1 selected source"}})
tmt("mv-resolution", "multi-viewer resolution: 3840x2160p60", {"multiview": {"resolution": "3840x2160p60"}})
tmt("vw-screen", "create vw screen 2x4", {"wall": {"rows": 2, "cols": 4}}, **M8)
tmt("vw-info-row", "row :2", {"wall": {"rows": 2}}, **M8)
tmt("vw-info-col", "col :4", {"wall": {"cols": 4}}, **M8)
tmt("vw-screen-output", "hdmi output 3->screen 3", {"wall": {"screens": {"3": {"output": 3}}}}, **M8)
tmt("vw-group-size", "vw group 1 row 1 col 2!", {"wall": {"groups": {"1": {"rows": 1, "cols": 2}}}}, **M8)
tmt("vw-group-screens", "vw group 2 screen 2367!", {"wall": {"groups": {"2": {"screens": "2367"}}}}, **M8)
tmt("vw-group-source", "vw group 1 source 1!", {"wall": {"groups": {"1": {"input": 1}}}}, **M8)
tmt("vw-group-h-bezel", "video wall group 1 h bezel: 0", {"wall": {"groups": {"1": {"h_bezel": 0}}}}, **M8)
tmt("vw-group-v-bezel", "video wall group 1 v bezel: 3", {"wall": {"groups": {"1": {"v_bezel": 3}}}}, **M8)
tmt("vw-group-resolution", "video wall group 1 resolution: 1920x1080p60",
    {"wall": {"groups": {"1": {"resolution": "1920x1080p60"}}}}, **M8)
tmt("vw-group-delete", "delete vw group 1!", {"wall": {"groups": {"2": {"input": 3}}}},
    state_before={"wall": {"groups": {"1": {"input": 1, "rows": 1}, "2": {"input": 3}}}}, **M8)
tmt("fans", "top fans:on", {"fans": {"top": True}}, **M8)
tmt("fans-set", "set top fans off", {"fans": {"top": False}}, **M8)
tmt("ip-mode", "ip mode: static", {"network": {"ip_mode": "static"}})
tmt("ip", "ip address:192.168.0.100", {"network": {"ip": "192.168.0.100"}})
tmt("subnet", "subnet mask: 255.255.255.0", {"network": {"subnet": "255.255.255.0"}})
tmt("gateway", "gateway:192.168.0.1", {"network": {"gateway": "192.168.0.1"}})
tmt("tcp-port", "tcp/ip port=8000", {"network": {"tcp_port": 8000}})
tmt("telnet-port", "telnet port:23", {"network": {"telnet_port": 23}})
tmt("mac", "mac address: 00:1c:91:03:80:01", {"network": {"mac": "00:1c:91:03:80:01"}})
tmt("type", "HDP-MXB88VW", {"model_name": "HDP-MXB88VW"}, request="r type!", **M8)
tmt("fast-reads", "power on", {"power": True}, request="r power!",
    expect_then_send=[x + "\r\n" for x in [
        "r output 1 in source!", "r output 2 in source!", "r output 3 in source!", "r output 4 in source!",
        "r display mode!"]])
