//! The NovaStar H series OpenAPI commands, kept in step with specs/novastar-h.yaml
//! (one entry per command there except `call`), from NovaStar's H Series OpenAPI pages.

/// A command: the endpoint after `/open/api/`, whether `deviceId` goes in the
/// body, the (parameter, JSON field) pairs copied into the body, and whether
/// a `body` parameter's fields are merged in.
pub(crate) struct Endpoint {
    pub name: &'static str,
    pub path: &'static str,
    pub device: bool,
    pub fields: &'static [(&'static str, &'static str)],
    pub body: bool,
}

pub(crate) const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        name: "read_device_detail",
        path: "device/readDetail",
        device: true,
        fields: &[],
        body: false,
    },
    Endpoint {
        name: "read_card_versions",
        path: "device/readCardVersion",
        device: true,
        fields: &[],
        body: false,
    },
    Endpoint {
        name: "read_device_ip",
        path: "device/readIp",
        device: true,
        fields: &[],
        body: false,
    },
    Endpoint {
        name: "read_init_status",
        path: "main/initStatus",
        device: false,
        fields: &[],
        body: false,
    },
    Endpoint {
        name: "list_screens",
        path: "screen/readList",
        device: true,
        fields: &[],
        body: false,
    },
    Endpoint {
        name: "get_screen",
        path: "screen/readDetail",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: false,
    },
    Endpoint {
        name: "get_screen_offline",
        path: "screen/nonTimeDetail",
        device: true,
        fields: &[],
        body: true,
    },
    Endpoint {
        name: "set_screen_brightness",
        path: "screen/writeBrightness",
        device: true,
        fields: &[("screen_id", "screenId"), ("brightness", "brightness")],
        body: false,
    },
    Endpoint {
        name: "save_screen_brightness",
        path: "screen/saveBrightness",
        device: true,
        fields: &[("screen_id", "screenId"), ("brightness", "brightness")],
        body: false,
    },
    Endpoint {
        name: "set_screen_gamma",
        path: "screen/writeGamma",
        device: true,
        fields: &[("screen_id", "screenId"), ("gamma", "gamma")],
        body: false,
    },
    Endpoint {
        name: "screen_ftb",
        path: "screen/ftb",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("type", "type"),
            ("seconds", "time"),
        ],
        body: false,
    },
    Endpoint {
        name: "set_screen_freeze",
        path: "screen/writeFreeze",
        device: true,
        fields: &[("screen_id", "screenId"), ("enable", "enable")],
        body: false,
    },
    Endpoint {
        name: "set_screen_bkg",
        path: "screen/writeBKG",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("enable", "enable"),
            ("bkg_id", "bkgId"),
        ],
        body: false,
    },
    Endpoint {
        name: "show_screen_ids",
        path: "screen/writeShowId",
        device: true,
        fields: &[("enable", "screenIdEnable")],
        body: false,
    },
    Endpoint {
        name: "rename_screen",
        path: "screen/rename",
        device: true,
        fields: &[("screen_id", "screenId"), ("name", "name")],
        body: false,
    },
    Endpoint {
        name: "delete_screens",
        path: "screen/deleteScreen",
        device: true,
        fields: &[("screen_ids", "screenIdList")],
        body: false,
    },
    Endpoint {
        name: "clear_screens",
        path: "screen/clear",
        device: true,
        fields: &[],
        body: false,
    },
    Endpoint {
        name: "create_screen",
        path: "screen/createScreen",
        device: true,
        fields: &[("name", "name")],
        body: true,
    },
    Endpoint {
        name: "set_screen_layout",
        path: "screen/writeOutputMode",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: true,
    },
    Endpoint {
        name: "set_screen_3d",
        path: "screen/write3D",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: true,
    },
    Endpoint {
        name: "set_text_osd",
        path: "screen/writeOSD",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: true,
    },
    Endpoint {
        name: "set_image_osd",
        path: "screen/writeImageOSD",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: true,
    },
    Endpoint {
        name: "list_inputs",
        path: "input/readList",
        device: true,
        fields: &[],
        body: false,
    },
    Endpoint {
        name: "get_input",
        path: "input/readDetail",
        device: true,
        fields: &[("input_id", "inputId")],
        body: false,
    },
    Endpoint {
        name: "rename_input",
        path: "input/rename",
        device: true,
        fields: &[("input_id", "inputId"), ("name", "name")],
        body: false,
    },
    Endpoint {
        name: "set_input_resolution",
        path: "input/writeResolution",
        device: true,
        fields: &[
            ("input_id", "inputId"),
            ("width", "width"),
            ("height", "height"),
            ("refresh_rate", "refreshRate"),
        ],
        body: false,
    },
    Endpoint {
        name: "set_input_timing",
        path: "input/writeTiming",
        device: true,
        fields: &[("input_id", "inputId")],
        body: true,
    },
    Endpoint {
        name: "create_input_crop",
        path: "input/writeCrop",
        device: true,
        fields: &[
            ("input_id", "inputId"),
            ("name", "name"),
            ("x", "x"),
            ("y", "y"),
            ("width", "width"),
            ("height", "height"),
        ],
        body: false,
    },
    Endpoint {
        name: "update_input_crop",
        path: "input/updateCrop",
        device: true,
        fields: &[
            ("input_id", "inputId"),
            ("crop_id", "cropId"),
            ("name", "name"),
            ("x", "x"),
            ("y", "y"),
            ("width", "width"),
            ("height", "heigth"),
        ],
        body: false,
    },
    Endpoint {
        name: "delete_input_crop",
        path: "input/deleteCrop",
        device: true,
        fields: &[("input_id", "inputId"), ("crop_id", "cropId")],
        body: false,
    },
    Endpoint {
        name: "create_input_group",
        path: "input/groupCreate",
        device: true,
        fields: &[("name", "inputGroupName")],
        body: true,
    },
    Endpoint {
        name: "update_input_group",
        path: "input/groupUpdate",
        device: true,
        fields: &[("group_id", "inputGroupId"), ("name", "inputGroupName")],
        body: true,
    },
    Endpoint {
        name: "sort_input_groups",
        path: "input/groupOrder",
        device: true,
        fields: &[],
        body: true,
    },
    Endpoint {
        name: "delete_input_group",
        path: "input/groupDelete",
        device: true,
        fields: &[("group_id", "inputGroupId")],
        body: false,
    },
    Endpoint {
        name: "remove_input_from_group",
        path: "input/groupNodeDelete",
        device: true,
        fields: &[("group_id", "inputGroupId"), ("input_id", "inputId")],
        body: false,
    },
    Endpoint {
        name: "import_edid",
        path: "input/importEDID",
        device: true,
        fields: &[
            ("input_id", "inputId"),
            ("file", "file"),
            ("file_name", "fileName"),
        ],
        body: false,
    },
    Endpoint {
        name: "list_source_playlists",
        path: "input/readSourceList",
        device: true,
        fields: &[],
        body: false,
    },
    Endpoint {
        name: "create_source_playlist",
        path: "input/createSource",
        device: true,
        fields: &[],
        body: true,
    },
    Endpoint {
        name: "update_source_playlist",
        path: "input/updateSource",
        device: true,
        fields: &[],
        body: true,
    },
    Endpoint {
        name: "enable_source_playlists",
        path: "input/enableSource",
        device: true,
        fields: &[],
        body: true,
    },
    Endpoint {
        name: "delete_source_playlists",
        path: "input/deleteSource",
        device: true,
        fields: &[("source_ids", "sourceIdList")],
        body: false,
    },
    Endpoint {
        name: "list_outputs",
        path: "output/readList",
        device: true,
        fields: &[],
        body: false,
    },
    Endpoint {
        name: "get_output",
        path: "output/readDetail",
        device: true,
        fields: &[("output_id", "outputId")],
        body: false,
    },
    Endpoint {
        name: "rename_output",
        path: "output/rename",
        device: true,
        fields: &[("output_id", "outputId"), ("name", "name")],
        body: false,
    },
    Endpoint {
        name: "set_output_gamma",
        path: "output/writeGamma",
        device: true,
        fields: &[("output_id", "outputId"), ("gamma", "gamma")],
        body: false,
    },
    Endpoint {
        name: "set_output_image_quality",
        path: "output/writeImageQuality",
        device: true,
        fields: &[("output_id", "outputId")],
        body: true,
    },
    Endpoint {
        name: "set_output_locating",
        path: "output/writeFixedPosition",
        device: true,
        fields: &[("enable", "enable")],
        body: false,
    },
    Endpoint {
        name: "set_output_resolution",
        path: "output/writeResolution",
        device: true,
        fields: &[
            ("output_ids", "outputIds"),
            ("width", "width"),
            ("height", "height"),
            ("refresh_rate", "refreshRate"),
        ],
        body: false,
    },
    Endpoint {
        name: "set_output_timing",
        path: "output/writeTiming",
        device: true,
        fields: &[
            ("output_ids", "outputIdList"),
            ("refresh_rate", "refreshRate"),
        ],
        body: true,
    },
    Endpoint {
        name: "set_4k_output_timing",
        path: "output/write4KTiming",
        device: true,
        fields: &[
            ("output_id", "outputId"),
            ("width", "width"),
            ("height", "height"),
            ("refresh_rate", "refreshRate"),
        ],
        body: true,
    },
    Endpoint {
        name: "set_all_in_one_payload",
        path: "output/writePayload",
        device: true,
        fields: &[
            ("output_ids", "outputIds"),
            ("width", "width"),
            ("height", "height"),
            ("refresh_rate", "refreshRate"),
        ],
        body: false,
    },
    Endpoint {
        name: "list_layers",
        path: "layer/detailList",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: false,
    },
    Endpoint {
        name: "get_layer",
        path: "layer/readDetail",
        device: true,
        fields: &[("screen_id", "screenId"), ("layer_id", "layerId")],
        body: false,
    },
    Endpoint {
        name: "get_layer_zorder",
        path: "layer/readZIndex",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: false,
    },
    Endpoint {
        name: "create_layer",
        path: "layer/create",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: true,
    },
    Endpoint {
        name: "delete_layer",
        path: "layer/delete",
        device: true,
        fields: &[("screen_id", "screenId"), ("layer_id", "layerId")],
        body: false,
    },
    Endpoint {
        name: "clear_layers",
        path: "layer/clear",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: false,
    },
    Endpoint {
        name: "set_layer_window",
        path: "layer/writeWindow",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("layer_id", "layerId"),
            ("x", "x"),
            ("y", "y"),
            ("width", "width"),
            ("height", "height"),
        ],
        body: false,
    },
    Endpoint {
        name: "set_layer_general",
        path: "layer/writeGeneral",
        device: true,
        fields: &[("screen_id", "screenId"), ("layer_id", "layerId")],
        body: true,
    },
    Endpoint {
        name: "set_layer_zorder",
        path: "layer/writeZIndex",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("layer_id", "layerId"),
            ("action", "layersZOrderAct"),
        ],
        body: false,
    },
    Endpoint {
        name: "lock_layer",
        path: "layer/writeLock",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("layer_id", "layerId"),
            ("lock", "lock"),
        ],
        body: false,
    },
    Endpoint {
        name: "set_layer_source",
        path: "layer/writeSource",
        device: true,
        fields: &[("screen_id", "screenId"), ("layer_id", "layerId")],
        body: true,
    },
    Endpoint {
        name: "freeze_layer",
        path: "layer/freeze",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("layer_id", "layerId"),
            ("enable", "enable"),
        ],
        body: false,
    },
    Endpoint {
        name: "open_layer_layout",
        path: "layer/screenLayerLayout",
        device: true,
        fields: &[],
        body: true,
    },
    Endpoint {
        name: "set_layer_stream_rule",
        path: "layer/writeStreamRule",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("layer_id", "layerId"),
            ("channel_id", "channelId"),
            ("stream_index", "streamIndex"),
        ],
        body: false,
    },
    Endpoint {
        name: "list_presets",
        path: "preset/readList",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: false,
    },
    Endpoint {
        name: "get_preset",
        path: "preset/readDetail",
        device: true,
        fields: &[("screen_id", "screenId"), ("preset_id", "presetId")],
        body: false,
    },
    Endpoint {
        name: "get_current_preset",
        path: "preset/readPlay",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: false,
    },
    Endpoint {
        name: "load_preset",
        path: "preset/play",
        device: true,
        fields: &[("screen_id", "screenId"), ("preset_id", "presetId")],
        body: false,
    },
    Endpoint {
        name: "create_preset",
        path: "preset/createPreset",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("name", "name"),
            ("overwrite", "overWrite"),
            ("layout_template_id", "layoutTemplateId"),
        ],
        body: false,
    },
    Endpoint {
        name: "overwrite_preset",
        path: "preset/overWrite",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("preset_id", "presetId"),
            ("name", "name"),
            ("overwrite", "overWrite"),
        ],
        body: false,
    },
    Endpoint {
        name: "rename_preset",
        path: "preset/writeGeneral",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("preset_id", "presetId"),
            ("name", "name"),
        ],
        body: false,
    },
    Endpoint {
        name: "delete_preset",
        path: "preset/deletePreset",
        device: true,
        fields: &[("screen_id", "screenId"), ("preset_id", "presetId")],
        body: false,
    },
    Endpoint {
        name: "clear_presets",
        path: "preset/deleteAll",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: false,
    },
    Endpoint {
        name: "list_preset_groups",
        path: "preset/groupList",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: false,
    },
    Endpoint {
        name: "get_preset_group",
        path: "preset/groupNodeList",
        device: true,
        fields: &[("screen_id", "screenId"), ("group_id", "presetGroupId")],
        body: false,
    },
    Endpoint {
        name: "create_preset_group",
        path: "preset/groupCreate",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("name", "name"),
            ("seconds", "time"),
        ],
        body: true,
    },
    Endpoint {
        name: "update_preset_group",
        path: "preset/groupUpdate",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("group_id", "presetGroupId"),
            ("name", "name"),
            ("seconds", "time"),
        ],
        body: true,
    },
    Endpoint {
        name: "delete_preset_group",
        path: "preset/groupDelete",
        device: true,
        fields: &[("screen_id", "screenId"), ("group_id", "presetGroupId")],
        body: false,
    },
    Endpoint {
        name: "play_preset_group",
        path: "preset/presetPoll",
        device: true,
        fields: &[
            ("screen_id", "screenId"),
            ("group_id", "presetGroupId"),
            ("enable", "enable"),
        ],
        body: false,
    },
    Endpoint {
        name: "get_preset_group_playing",
        path: "preset/readPresetPoll",
        device: true,
        fields: &[("screen_id", "screenId")],
        body: false,
    },
    Endpoint {
        name: "list_bkgs",
        path: "bkg/readAllList",
        device: true,
        fields: &[],
        body: false,
    },
    Endpoint {
        name: "get_bkg",
        path: "bkg/readDetail",
        device: true,
        fields: &[("bkg_id", "bkgId")],
        body: false,
    },
    Endpoint {
        name: "create_bkg",
        path: "bkg/create",
        device: true,
        fields: &[
            ("name", "name"),
            ("file_name", "fileName"),
            ("file", "file"),
        ],
        body: false,
    },
    Endpoint {
        name: "delete_bkgs",
        path: "bkg/delete",
        device: true,
        fields: &[("bkg_ids", "bkgIdList")],
        body: false,
    },
];
